-- Orbital — all migrations, concatenated for a single paste.
--
-- Generated by `npm run migrations:bundle` from supabase/migrations/.
-- Do not edit: edit the individual migrations and regenerate.
--
-- Paste the whole file into the Supabase SQL Editor and run it once.
-- Every statement is idempotent, so re-running after a partial failure is
-- safe and is the intended recovery path.
--
-- Files, in order:
--   0001_initial_schema.sql
--   0002_storage.sql
--   0003_builder_core.sql
--   0004_durable_runs.sql
--   0005_worker_and_concurrency.sql
--   0006_retry_and_history.sql
--   0007_validation_record.sql

begin;

-- ============================================================================
-- 0001_initial_schema.sql
-- ============================================================================

-- Orbital — initial schema
--
-- Apply with the Supabase CLI (`supabase db push`) or by pasting into the SQL
-- editor of a new project. Idempotent: safe to re-run.
--
-- Model. Every user gets a personal workspace on sign-up, created by a
-- trigger. That is how "my projects" is expressed today, while leaving the
-- shape in place for shared workspaces later without a migration of the
-- projects table.
--
-- Security. Row Level Security is the real boundary. The service layer also
-- checks roles, but that is for good error messages; if a service is ever
-- bypassed these policies still hold. Projects are owner-only today, matching
-- the requirement that a user can only reach their own.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- tables --

create table if not exists public.workspaces (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (char_length(name) between 1 and 80),
  slug        text not null unique,
  created_at  timestamptz not null default now()
);

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  user_id      uuid not null references auth.users (id) on delete cascade,
  role         text not null default 'member'
               check (role in ('owner', 'admin', 'member', 'viewer')),
  joined_at    timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create table if not exists public.projects (
  id                  uuid primary key default gen_random_uuid(),
  workspace_id        uuid not null references public.workspaces (id) on delete cascade,
  -- Denormalised beside workspace_id so a row can be authorised without a
  -- join. The RLS policies below depend on it.
  owner_id            uuid not null references auth.users (id) on delete cascade,
  name                text not null check (char_length(name) between 1 and 60),
  description         text check (description is null or char_length(description) <= 280),
  status              text not null default 'draft'
                      check (status in ('draft', 'generating', 'ready', 'failed')),
  -- Revisions arrive with the generation engine. Left nullable and
  -- unconstrained so that table can be added without altering this one.
  current_revision_id uuid,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists projects_workspace_updated_idx
  on public.projects (workspace_id, updated_at desc);
create index if not exists projects_owner_idx
  on public.projects (owner_id);
create index if not exists workspace_members_user_idx
  on public.workspace_members (user_id);

-- -------------------------------------------------------------- triggers --

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_touch_updated_at on public.projects;
create trigger projects_touch_updated_at
  before update on public.projects
  for each row execute function public.touch_updated_at();

-- Personal workspace on sign-up.
--
-- security definer because the trigger runs before the new user has any
-- session, so RLS would reject both inserts. search_path is pinned so the
-- elevated function cannot be redirected at a shadowed schema.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_workspace_id uuid;
  label text;
begin
  label := coalesce(
    nullif(new.raw_user_meta_data ->> 'display_name', ''),
    split_part(coalesce(new.email, 'account'), '@', 1)
  );

  insert into public.workspaces (name, slug)
  values (
    left(label, 60) || '''s workspace',
    'w-' || replace(new.id::text, '-', '')
  )
  returning id into new_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (new_workspace_id, new.id, 'owner');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ------------------------------------------------------------------- RLS --

alter table public.workspaces        enable row level security;
alter table public.workspace_members enable row level security;
alter table public.projects          enable row level security;

-- A user sees only their own membership rows. Deliberately not "rows for any
-- workspace I belong to": that form makes the policy query its own table and
-- recurse.
drop policy if exists workspace_members_select_own on public.workspace_members;
create policy workspace_members_select_own
  on public.workspace_members for select
  using (user_id = auth.uid());

-- Workspaces are visible when the caller has a membership row. This reads
-- workspace_members, whose policy does not read workspaces, so there is no
-- cycle.
drop policy if exists workspaces_select_member on public.workspaces;
create policy workspaces_select_member
  on public.workspaces for select
  using (
    exists (
      select 1 from public.workspace_members m
      where m.workspace_id = workspaces.id
        and m.user_id = auth.uid()
    )
  );

-- Projects: owner only, for every verb.
--
-- The insert check pins owner_id to the caller, so a forged owner_id in the
-- request body is rejected by the database rather than trusted. The update
-- policy repeats it in `with check` so ownership cannot be reassigned.
drop policy if exists projects_select_own on public.projects;
create policy projects_select_own
  on public.projects for select
  using (owner_id = auth.uid());

drop policy if exists projects_insert_own on public.projects;
create policy projects_insert_own
  on public.projects for insert
  with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.workspace_members m
      where m.workspace_id = projects.workspace_id
        and m.user_id = auth.uid()
    )
  );

drop policy if exists projects_update_own on public.projects;
create policy projects_update_own
  on public.projects for update
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists projects_delete_own on public.projects;
create policy projects_delete_own
  on public.projects for delete
  using (owner_id = auth.uid());


-- ============================================================================
-- 0002_storage.sql
-- ============================================================================

-- Orbital — artifact storage
--
-- The bucket holds user uploads: sketches, screenshots, PDFs and audio.
--
-- It is private and has no policies for authenticated users, which under RLS
-- means only the service role can reach it. That is deliberate. Uploads and
-- reads both go through short-lived signed URLs minted server-side in
-- lib/server/supabase/storage.ts, after the request has been authorised by the
-- service layer. Adding a permissive policy here would create a second,
-- unaudited way in.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'orbital-artifacts',
  'orbital-artifacts',
  false,
  26214400, -- 25 MB, matching MAX_UPLOAD_BYTES in lib/domain/input.ts
  array[
    'image/png', 'image/jpeg', 'image/webp', 'image/avif',
    'application/pdf',
    'audio/webm', 'audio/mpeg', 'audio/wav', 'audio/mp4'
  ]
)
on conflict (id) do update
  set file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types,
      public             = excluded.public;


-- ============================================================================
-- 0003_builder_core.sql
-- ============================================================================

-- Orbital — builder core
--
-- STATUS: proposed, not yet wired.
--
-- No adapter reads or writes these tables. lib/server/container.ts still
-- resolves files, runs and revisions to the unconfigured adapters on the
-- Supabase path, which throw NotConfiguredError. Applying this migration adds
-- the tables; it does not turn the capability on. That happens when
-- lib/server/supabase/ gains repositories implementing ProjectFileRepository,
-- RunRepository and RevisionRepository.
--
-- It is written now because the shape is what Milestone 1 had to decide, and
-- deciding it in TypeScript while leaving the database to guess later is how
-- the two drift.
--
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------- tables --

-- The working tree. One row per file per project.
--
-- Content is inline text. Binary assets carry a storage_key and leave content
-- null — the same split as domain/file.ts, for the same reason: the model
-- reads and writes text, and putting a 4MB image in a text column to keep the
-- shape uniform would be paying a real cost for a cosmetic one.
create table if not exists public.project_files (
  project_id  uuid not null references public.projects (id) on delete cascade,
  path        text not null check (char_length(path) between 1 and 400),
  kind        text not null default 'text' check (kind in ('text', 'binary')),
  content     text,
  storage_key text,
  hash        text not null,
  byte_size   integer not null default 0 check (byte_size >= 0),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (project_id, path),
  -- Exactly one of the two carries the bytes.
  constraint project_files_content_xor_key check (
    (kind = 'text'   and content is not null and storage_key is null) or
    (kind = 'binary' and content is null     and storage_key is not null)
  )
);

create index if not exists project_files_project_idx
  on public.project_files (project_id);

-- Revisions. Promoted from "arrives with the generation engine" in 0001.
--
-- `tree` is the frozen snapshot as jsonb. A full snapshot rather than a diff:
-- restoring a revision must not depend on replaying every revision before it,
-- and at the size of a generated site the storage cost is not worth the
-- fragility. Diffs are computed between snapshots on read, not stored.
create table if not exists public.project_revisions (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid not null references public.projects (id) on delete cascade,
  parent_id     uuid references public.project_revisions (id) on delete set null,
  generation_id uuid,
  summary       text not null default '',
  tree          jsonb not null default '[]'::jsonb,
  -- The legacy GeneratedSite blob. Kept so the existing preview route keeps
  -- working during the transition; drop it once the preview reads the tree.
  site          jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists project_revisions_project_created_idx
  on public.project_revisions (project_id, created_at desc);

-- Generation runs. The audit trail: what was asked, what was planned, which
-- operations came back and what happened to each.
create table if not exists public.generation_runs (
  id                   uuid primary key default gen_random_uuid(),
  project_id           uuid not null references public.projects (id) on delete cascade,
  generation_id        uuid,
  prompt               text not null default '',
  base_revision_id     uuid references public.project_revisions (id) on delete set null,
  produced_revision_id uuid references public.project_revisions (id) on delete set null,
  status               text not null default 'queued'
                       check (status in ('queued','reading','understanding','building',
                                         'succeeded','failed','cancelled')),
  plan                 jsonb,
  operations           jsonb not null default '[]'::jsonb,
  report               jsonb,
  -- Null when no model was involved, which is the honest record for anything
  -- the template engine produced.
  model                jsonb,
  events               jsonb not null default '[]'::jsonb,
  error                text,
  created_at           timestamptz not null default now(),
  completed_at         timestamptz
);

create index if not exists generation_runs_project_created_idx
  on public.generation_runs (project_id, created_at desc);

-- -------------------------------------------------------------- triggers --

drop trigger if exists project_files_touch_updated_at on public.project_files;
create trigger project_files_touch_updated_at
  before update on public.project_files
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------------- RLS --
--
-- All three tables are reached only through their project, so every policy is
-- the same question: does the caller own the project this row belongs to?
-- Written as an EXISTS against projects, whose own policy is already
-- owner-only, so there is no new trust path and no policy recursion.

alter table public.project_files     enable row level security;
alter table public.project_revisions enable row level security;
alter table public.generation_runs   enable row level security;

drop policy if exists project_files_own on public.project_files;
create policy project_files_own
  on public.project_files for all
  using (
    exists (
      select 1 from public.projects p
      where p.id = project_files.project_id and p.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.projects p
      where p.id = project_files.project_id and p.owner_id = auth.uid()
    )
  );

drop policy if exists project_revisions_own on public.project_revisions;
create policy project_revisions_own
  on public.project_revisions for all
  using (
    exists (
      select 1 from public.projects p
      where p.id = project_revisions.project_id and p.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.projects p
      where p.id = project_revisions.project_id and p.owner_id = auth.uid()
    )
  );

drop policy if exists generation_runs_own on public.generation_runs;
create policy generation_runs_own
  on public.generation_runs for all
  using (
    exists (
      select 1 from public.projects p
      where p.id = generation_runs.project_id and p.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.projects p
      where p.id = generation_runs.project_id and p.owner_id = auth.uid()
    )
  );

-- ------------------------------------------------------------ constraint --
--
-- 0001 left projects.current_revision_id unconstrained because the table it
-- points at did not exist. It does now.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'projects_current_revision_fk'
  ) then
    alter table public.projects
      add constraint projects_current_revision_fk
      foreign key (current_revision_id)
      references public.project_revisions (id)
      on delete set null;
  end if;
end $$;


-- ============================================================================
-- 0004_durable_runs.sql
-- ============================================================================

-- Orbital — durable generation runs
--
-- 0003 proposed the builder-core tables while generation still ran inline. The
-- pipeline made a run into a job that outlives the request that created it, so
-- the row needs the state a worker reads on the way back in: what it was asked
-- to do, who is holding it, when they took it, and why it failed.
--
-- Idempotent: safe to re-run. Assumes 0003 has been applied.

-- ------------------------------------------------------- generation_runs --

alter table public.generation_runs
  -- The original request. A durable run must be resumable from its own row,
  -- not from whatever was in the submitting request's memory.
  add column if not exists intent jsonb not null default '{}'::jsonb,
  -- demo | model. Recorded per run so history cannot imply a model was
  -- involved when none was.
  add column if not exists mode text not null default 'demo'
    check (mode in ('demo', 'model')),
  -- Deduplicates accidental double submissions.
  add column if not exists idempotency_key text,
  -- When a worker first claimed the run.
  add column if not exists started_at timestamptz,
  -- Lease held by the worker currently advancing this run. A row whose lease
  -- has passed was abandoned by a dead process and may be reclaimed; this is
  -- what makes the pipeline durable without a queue service.
  add column if not exists lease_expires_at timestamptz,
  -- Structured failure: { stage, message, validation? }. Never a credential —
  -- provider errors are translated at the adapter boundary before they reach
  -- here, precisely so an API key cannot end up persisted in a run row.
  add column if not exists failure jsonb;

-- The status set grew with the pipeline: running and validating are real
-- persisted states now, not just event labels.
alter table public.generation_runs drop constraint if exists generation_runs_status_check;
alter table public.generation_runs
  add constraint generation_runs_status_check
  check (status in (
    'queued', 'running', 'reading', 'understanding', 'building',
    'validating', 'succeeded', 'failed', 'cancelled'
  ));

-- Idempotency is enforced by the database, not by a read-then-write in
-- application code: two simultaneous submits would both see "no existing run"
-- and both insert. A unique index makes the second one fail instead.
create unique index if not exists generation_runs_idempotency_idx
  on public.generation_runs (project_id, idempotency_key)
  where idempotency_key is not null;

-- Backs findActive and the claim query.
create index if not exists generation_runs_active_idx
  on public.generation_runs (project_id, status)
  where status not in ('succeeded', 'failed', 'cancelled');

create index if not exists generation_runs_generation_idx
  on public.generation_runs (generation_id);

-- ------------------------------------------------------ atomic claim ------
--
-- The concurrency primitive. Doing this as SELECT-then-UPDATE in TypeScript
-- would leave a window where two workers both see a free lease and both take
-- it; a single conditional UPDATE cannot. Returns the row only to the caller
-- that won.
--
-- security definer with a pinned search_path, and it re-checks ownership
-- itself — it must not become a way to touch another user's run.
create or replace function public.claim_generation_run(
  p_run_id uuid,
  p_lease_ms integer
)
returns setof public.generation_runs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.generation_runs r
     set status           = 'running',
         started_at       = coalesce(r.started_at, now()),
         lease_expires_at = now() + make_interval(secs => p_lease_ms / 1000.0)
   where r.id = p_run_id
     and r.status not in ('succeeded', 'failed', 'cancelled')
     and (r.lease_expires_at is null or r.lease_expires_at < now())
     and exists (
       select 1 from public.projects p
       where p.id = r.project_id and p.owner_id = auth.uid()
     )
  returning r.*;
end;
$$;

revoke all on function public.claim_generation_run(uuid, integer) from public;
grant execute on function public.claim_generation_run(uuid, integer) to authenticated;

-- ---------------------------------------------------------- revisions -----

-- Restore reads this; a revision without one can be shown but not restored.
alter table public.project_revisions
  add column if not exists tree jsonb not null default '[]'::jsonb;


-- ============================================================================
-- 0005_worker_and_concurrency.sql
-- ============================================================================

-- Orbital — worker trigger and the active-run invariant
--
-- Two gaps left by 0004:
--
--   1. `findActive` was advisory. It was a plain SELECT, so two submits
--      arriving in the same instant could both read "no active run" and both
--      insert. Application code cannot close that window; only a constraint
--      can.
--
--   2. `claim_generation_run` required `auth.uid()` to own the project, which
--      is right for a user polling their own run and wrong for a worker. A
--      scheduler has no session, so under 0004 it could never claim anything.
--
-- Idempotent: safe to re-run. Assumes 0003 and 0004 have been applied.

-- ------------------------------------------- one active run per project ---
--
-- A partial unique index is the whole mechanism. Postgres refuses the second
-- concurrent insert rather than the application noticing afterwards, so the
-- invariant holds under any interleaving, including two separate processes.
--
-- Terminal runs are excluded, so a project accumulates history freely and only
-- ever has at most one row in flight.
--
-- Note this deliberately does NOT exclude expired leases: an index predicate
-- must be immutable, and `now()` is not. Stale runs are handled where they can
-- be — `listClaimable` treats an expired lease as claimable, so a worker takes
-- the abandoned run over rather than a new one being created beside it.
create unique index if not exists generation_runs_one_active_per_project
  on public.generation_runs (project_id)
  where status not in ('succeeded', 'failed', 'cancelled');

-- ------------------------------------------------------ worker claiming ---
--
-- Replaces the 0004 definition. Same conditional UPDATE — still the only place
-- the lease decision can be made atomically — but the ownership test now
-- accepts either the project's owner (a user polling their own run) or the
-- service role (a worker draining the queue).
--
-- security definer with a pinned search_path, so the elevated function cannot
-- be redirected at a shadowed schema.
create or replace function public.claim_generation_run(
  p_run_id uuid,
  p_lease_ms integer
)
returns setof public.generation_runs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.generation_runs r
     set status           = 'running',
         started_at       = coalesce(r.started_at, now()),
         lease_expires_at = now() + make_interval(secs => p_lease_ms / 1000.0)
   where r.id = p_run_id
     and r.status not in ('succeeded', 'failed', 'cancelled')
     and (r.lease_expires_at is null or r.lease_expires_at < now())
     and (
       -- The worker: no session, acts on the whole queue.
       auth.role() = 'service_role'
       -- Or the owner, polling their own run.
       or exists (
         select 1 from public.projects p
         where p.id = r.project_id and p.owner_id = auth.uid()
       )
     )
  returning r.*;
end;
$$;

revoke all on function public.claim_generation_run(uuid, integer) from public;
grant execute on function public.claim_generation_run(uuid, integer) to authenticated;
grant execute on function public.claim_generation_run(uuid, integer) to service_role;

-- ------------------------------------------------------- worker inbox -----
--
-- Backs listClaimable: queued runs and runs whose lease has lapsed, oldest
-- first. Partial so it stays small no matter how much history accumulates.
create index if not exists generation_runs_claimable_idx
  on public.generation_runs (created_at)
  where status not in ('succeeded', 'failed', 'cancelled');


-- ============================================================================
-- 0006_retry_and_history.sql
-- ============================================================================

-- 0006 — retry lineage and queryable history.
--
-- Two things: a run can now record that it retries another one, and history
-- can be paged efficiently instead of being capped at "the most recent few".
--
-- Safe to run against a database already carrying 0001–0005. Every statement
-- is idempotent, and the new columns are nullable or defaulted, so existing
-- rows stay valid without a backfill.

-- ------------------------------------------------------ retry lineage -----
--
-- A retry is a new run pointing at the one that failed, never an edit of it —
-- the failure has to stay in history or the history is not a record. The
-- reference is `on delete set null` rather than cascade: deleting a run must
-- not silently take its retries with it.
alter table public.generation_runs
  add column if not exists retry_of_run_id uuid
    references public.generation_runs (id) on delete set null;

-- 1 for a first attempt, 2 for its first retry. Defaulted so rows written
-- before this migration read as first attempts, which is what they were.
alter table public.generation_runs
  add column if not exists attempt integer not null default 1;

alter table public.generation_runs
  drop constraint if exists generation_runs_attempt_positive;
alter table public.generation_runs
  add constraint generation_runs_attempt_positive check (attempt >= 1);

-- A run may not retry itself. Cheap to state, and the alternative is a cycle
-- that makes lineage walks non-terminating.
alter table public.generation_runs
  drop constraint if exists generation_runs_retry_not_self;
alter table public.generation_runs
  add constraint generation_runs_retry_not_self check (retry_of_run_id is null or retry_of_run_id <> id);

-- Finding the retries of a run. Partial, because the overwhelming majority of
-- runs are not retries and there is no reason to index their nulls.
create index if not exists generation_runs_retry_of_idx
  on public.generation_runs (retry_of_run_id)
  where retry_of_run_id is not null;

-- ---------------------------------------------------- history queries -----
--
-- Backs RunRepository.query: filter by project, order by created_at
-- descending, page with a keyset cursor. The composite index the cursor needs
-- — `(project_id, created_at desc)` — already exists as
-- `generation_runs_project_created_idx`, created in 0003. It is what makes the
-- cursor an index seek rather than a scan-and-discard, so it is load-bearing
-- for paging even though this migration does not create it.

-- Status filtering within a project ("show me only the failures"). Separate
-- from the index above because leading with status would make the common
-- unfiltered query use a worse plan.
create index if not exists generation_runs_project_status_created_idx
  on public.generation_runs (project_id, status, created_at desc);

-- Finding the run that produced a given revision — the link the diff view
-- follows from a revision back to its generation.
create index if not exists generation_runs_produced_revision_idx
  on public.generation_runs (produced_revision_id)
  where produced_revision_id is not null;

comment on column public.generation_runs.retry_of_run_id is
  'The run this one retries. Points at the lineage root, not the immediate predecessor.';
comment on column public.generation_runs.attempt is
  'Attempt number, from 1. Part of the idempotency key so a retry does not collide with the original.';


-- ============================================================================
-- 0007_validation_record.sql
-- ============================================================================

-- 0007 — the validator's verdict, on success as well as failure.
--
-- Validation already ran on every generation, but its result was only kept
-- when it *refused*, tucked inside `failure.validation`. So a change that was
-- applied with warnings — a page linking to something nobody wrote, say — had
-- those warnings computed and then thrown away, which made the checks
-- invisible exactly when they were informative rather than fatal.
--
-- Safe to run against a database carrying 0001–0006. Nullable, so existing
-- rows stay valid; they read as "no validation recorded", which is true.

alter table public.generation_runs
  add column if not exists validation jsonb;

comment on column public.generation_runs.validation is
  'ValidationResult for this run: errors, warnings and how many operations were checked. Recorded whether or not it passed.';

commit;
