/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import type { Refs, Vals } from "./types";
import { Background } from "./sections/Background";
import { SiteHeader } from "./sections/SiteHeader";
import { SiteFooter } from "./sections/SiteFooter";
import { Hero } from "./sections/Hero";
import { Triad } from "./sections/Triad";
import { HowItWorks } from "./sections/HowItWorks";
import { InteractiveDemo } from "./sections/InteractiveDemo";
import { ConversationalEditing } from "./sections/ConversationalEditing";
import { ChaptersIntro } from "./sections/ChaptersIntro";
import { ChapterInput } from "./sections/ChapterInput";
import { ChapterUnderstanding } from "./sections/ChapterUnderstanding";
import { ChapterBuild } from "./sections/ChapterBuild";
import { ChapterProduct } from "./sections/ChapterProduct";
import { Workspace } from "./sections/Workspace";
import { Comparison } from "./sections/Comparison";
import { Timeline } from "./sections/Timeline";
import { Pricing } from "./sections/Pricing";
import { Faq } from "./sections/Faq";
import { CallToAction } from "./sections/CallToAction";

export function Template({ v, starRef, globeRef, cometRef, navRef, heroStageRef }: { v: Vals } & Refs) {
  return (
    <div style={{ position: "relative", minHeight: "100vh", isolation: "isolate" }}>
      <Background starRef={starRef} globeRef={globeRef} cometRef={cometRef} />
      <SiteHeader navRef={navRef} />
      <main style={{ position: "relative", zIndex: "10" }}>
        <Hero v={v} heroStageRef={heroStageRef} />
        <Triad v={v} />
        <HowItWorks v={v} />
        <InteractiveDemo v={v} />
        <ConversationalEditing v={v} />
        <ChaptersIntro />
        <ChapterInput v={v} />
        <ChapterUnderstanding v={v} />
        <ChapterBuild v={v} />
        <ChapterProduct v={v} />
        <Workspace v={v} />
        <Comparison v={v} />
        <Timeline v={v} />
        <Pricing v={v} />
        <Faq v={v} />
        <CallToAction />
        <SiteFooter />
      </main>
    </div>
  );
}
