/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */


export function CallToAction() {
  return (
      <section className="r-section r-pad-lg" id="cta" style={{ position: "relative", padding: "0 28px 110px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", position: "relative", borderRadius: "26px", border: "1px solid rgba(255,255,255,.1)", overflow: "hidden", background: "radial-gradient(800px 380px at 50% -20%,rgba(124,230,255,.18),rgba(255,255,255,.015) 70%)" }}>
          <div style={{ padding: "80px 40px 84px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}>
            <div style={{ position: "relative", width: "220px", height: "150px" }}>
              <div style={{ position: "absolute", inset: "0", borderRadius: "3px", background: "linear-gradient(178deg,#f2efe6,#e2ded1)", boxShadow: "0 26px 60px rgba(0,0,0,.55)", transform: "rotate(-6deg)", padding: "16px", display: "flex", flexDirection: "column", gap: "8px" }}>
                <span style={{ height: "14px", border: "2px solid #55565a", borderRadius: "2px" }} />
                <span style={{ flex: "1", border: "2px solid #55565a", borderRadius: "2px" }} />
                <span style={{ height: "26px", border: "2px solid #55565a", borderRadius: "2px" }} />
              </div>
              <div style={{ position: "absolute", inset: "0", borderRadius: "10px", border: "1px solid rgba(190,240,255,.4)", background: "linear-gradient(165deg,rgba(16,24,38,.96),rgba(8,11,18,.98))", boxShadow: "0 30px 70px rgba(0,0,0,.6)", transform: "rotate(4deg) translate(26px,14px)", padding: "14px", display: "flex", flexDirection: "column", gap: "8px", animation: "floaty 7s ease-in-out infinite" }}>
                <span style={{ height: "12px", borderRadius: "4px", background: "rgba(255,255,255,.12)" }} />
                <span style={{ flex: "1", borderRadius: "6px", background: "linear-gradient(150deg,rgba(143,230,255,.22),rgba(164,139,255,.14))" }} />
                <span style={{ height: "20px", width: "70px", borderRadius: "6px", background: "linear-gradient(180deg,#d6f4ff,#8ad9ff)" }} />
              </div>
            </div>
            <h2 style={{ margin: "48px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(30px,4.4vw,58px)", letterSpacing: "-.035em", lineHeight: "1.02" }}>
              {"Your idea is "}
              <span style={{ fontFamily: "'Instrument Serif',serif", fontStyle: "italic", fontWeight: "400", color: "#cdeaff" }}>
                {"already"}
              </span>
              {" enough."}
            </h2>
            <p style={{ margin: "20px 0 0", maxWidth: "430px", fontSize: "15.5px", lineHeight: "1.65", color: "rgba(233,235,242,.58)" }}>
              {"Bring the napkin. Free while we're in orbit."}
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "11px", justifyContent: "center", marginTop: "34px" }}>
              <a href="/sign-up" style={{ display: "inline-flex", alignItems: "center", gap: "10px", padding: "15px 27px", borderRadius: "999px", fontSize: "15px", fontWeight: "500", color: "#04060c", background: "linear-gradient(180deg,#cdf3ff,#7ad6ff)", boxShadow: "0 16px 46px rgba(122,214,255,.32)" }} className="orb-h12">
                {"Start building "}
                <span style={{ fontFamily: "'IBM Plex Mono',monospace" }}>
                  {"→"}
                </span>
              </a>
              <a href="#demo" style={{ display: "inline-flex", alignItems: "center", gap: "10px", padding: "15px 24px", borderRadius: "999px", fontSize: "15px", border: "1px solid rgba(255,255,255,.14)", background: "rgba(255,255,255,.03)" }} className="orb-h3">
                {"Watch the demo"}
              </a>
            </div>
          </div>
        </div>
      </section>
  );
}
