/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function ChapterBuild({ v }: { v: Vals }) {
  return (
      <section className="r-section r-pad-lg" style={{ position: "relative", padding: "0 0 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", padding: "0 28px" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: "18px", marginBottom: "34px" }}>
            <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".18em", color: "rgba(124,230,255,.8)" }}>
              {"CHAPTER 03"}
            </span>
            <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(24px,3vw,38px)", letterSpacing: "-.03em" }}>
              {"Build"}
            </span>
            <span style={{ flex: "1", height: "1px", background: "linear-gradient(90deg,rgba(255,255,255,.16),transparent)" }} />
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,.85fr) minmax(0,1.15fr)", gap: "0", border: "1px solid rgba(255,255,255,.09)", borderRadius: "20px", overflow: "hidden", background: "rgba(8,11,18,.72)" }} className="r-2col">
            <div style={{ padding: "26px", borderRight: "1px solid rgba(255,255,255,.07)", background: "rgba(255,255,255,.018)" }}>
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(233,235,242,.4)" }}>
                {"Component tree"}
              </div>
              <div style={{ marginTop: "16px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "11.5px", lineHeight: "2", color: "rgba(233,235,242,.62)" }}>
                {v.tree.map((tn, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ paddingLeft: tn.pad, color: tn.color }}>
                      {tn.t}
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "24px", paddingTop: "18px", borderTop: "1px solid rgba(255,255,255,.07)", display: "flex", flexWrap: "wrap", gap: "7px" }}>
                {v.exportTargets.map((et, i0) => (
                  <React.Fragment key={i0}>
                    <span style={{ padding: "6px 10px", borderRadius: "8px", border: "1px solid rgba(255,255,255,.1)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.6)" }} className="orb-h6 r-touch">
                      {et}
                    </span>
                  </React.Fragment>
                ))}
              </div>
            </div>
            <div style={{ padding: "26px" }}>
              <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                {v.chapterBuild.map((cb, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: "20px", alignItems: "center", padding: "18px 20px", borderRadius: "14px", border: "1px solid rgba(255,255,255,.08)", background: cb.bg }}>
                      <div>
                        <div style={{ display: "flex", alignItems: "baseline", gap: "10px" }}>
                          <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(124,230,255,.8)" }}>
                            {cb.n}
                          </span>
                          <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "18px", letterSpacing: "-.02em" }}>
                            {cb.t}
                          </span>
                        </div>
                        <div style={{ marginTop: "7px", fontSize: "13px", lineHeight: "1.55", color: "rgba(233,235,242,.52)", maxWidth: "380px" }}>
                          {cb.d}
                        </div>
                      </div>
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.4)", textAlign: "right", whiteSpace: "pre-line" }}>
                        {cb.k}
                      </span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>
  );
}
