/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */


export function ChaptersIntro() {
  return (
      <section id="chapters" style={{ position: "relative", padding: "0 28px 40px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "30px", flexWrap: "wrap", borderBottom: "1px solid rgba(255,255,255,.09)", paddingBottom: "22px" }}>
            <h2 style={{ margin: "0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(28px,3.6vw,46px)", letterSpacing: "-.03em" }}>
              {"Twenty-six capabilities,"}
              <br />
              {"four chapters."}
            </h2>
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".14em", color: "rgba(233,235,242,.36)", textTransform: "uppercase" }}>
              {"F01 — F26"}
            </div>
          </div>
        </div>
      </section>
  );
}
