/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function ChapterProduct({ v }: { v: Vals }) {
  return (
      <section style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: "18px", marginBottom: "34px" }}>
            <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".18em", color: "rgba(164,139,255,.85)" }}>
              {"CHAPTER 04"}
            </span>
            <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(24px,3vw,38px)", letterSpacing: "-.03em" }}>
              {"Product"}
            </span>
            <span style={{ flex: "1", height: "1px", background: "linear-gradient(90deg,rgba(255,255,255,.16),transparent)" }} />
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(12,1fr)", gap: "16px" }}>
            <div style={{ gridColumn: "span 7", minWidth: "0", padding: "28px", borderRadius: "20px", border: "1px solid rgba(255,255,255,.09)", background: "linear-gradient(150deg,rgba(124,230,255,.08),rgba(255,255,255,.015))" }}>
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", color: "rgba(124,230,255,.8)" }}>
                {"F20 · F21 — PRODUCT INTELLIGENCE + 3D"}
              </div>
              <h3 style={{ margin: "16px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "26px", letterSpacing: "-.025em" }}>
                {"A photo of a watch isn't an image. It's a storefront."}
              </h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginTop: "22px", alignItems: "stretch" }}>
                <div style={{ borderRadius: "14px", border: "1px solid rgba(255,255,255,.1)", background: "repeating-linear-gradient(128deg,rgba(255,255,255,.06) 0 9px,rgba(255,255,255,.02) 9px 18px)", minHeight: "186px", display: "flex", alignItems: "flex-end", padding: "12px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(233,235,242,.45)" }}>
                  {"product photo · drop here"}
                </div>
                <div style={{ borderRadius: "14px", border: "1px solid rgba(124,230,255,.3)", background: "radial-gradient(circle at 50% 42%,rgba(124,230,255,.18),rgba(255,255,255,.02) 68%)", minHeight: "186px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "14px", perspective: "600px" }}>
                  <span style={{ width: "96px", height: "96px", borderRadius: "16px", border: "1px solid rgba(190,240,255,.5)", background: "linear-gradient(150deg,rgba(190,240,255,.14),rgba(164,139,255,.1))", animation: "spinSlow 12s linear infinite", transformStyle: "preserve-3d" }} />
                  <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(190,240,255,.85)" }}>
                    {"3D viewer · drag to orbit"}
                  </span>
                </div>
              </div>
              <div style={{ marginTop: "18px", display: "flex", flexWrap: "wrap", gap: "8px" }}>
                {v.productOffers.map((po, i0) => (
                  <React.Fragment key={i0}>
                    <span style={{ padding: "8px 13px", borderRadius: "999px", border: `1px solid ${po.border}`, background: po.bg, fontSize: "12.5px", color: po.color, cursor: "pointer" }} className="orb-h7">
                      {po.t}
                    </span>
                  </React.Fragment>
                ))}
              </div>
            </div>
            <div style={{ gridColumn: "span 5", minWidth: "0", padding: "28px", borderRadius: "20px", border: "1px solid rgba(255,255,255,.09)", background: "rgba(255,255,255,.028)" }}>
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", color: "rgba(164,139,255,.85)" }}>
                {"F23 · F24 · F25 — SIMULATE, AUDIT, RANK"}
              </div>
              <h3 style={{ margin: "16px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "22px", letterSpacing: "-.02em" }}>
                {"Simulated users before real ones."}
              </h3>
              <div style={{ marginTop: "20px", display: "flex", flexDirection: "column", gap: "13px" }}>
                {v.uxMetrics.map((um, i0) => (
                  <React.Fragment key={i0}>
                    <div>
                      <div style={{ display: "flex", justifyContent: "space-between", fontSize: "12.5px", color: "rgba(233,235,242,.6)" }}>
                        <span>
                          {um.t}
                        </span>
                        <span style={{ fontFamily: "'IBM Plex Mono',monospace", color: "rgba(233,235,242,.88)" }}>
                          {um.v}
                        </span>
                      </div>
                      <div style={{ marginTop: "6px", height: "3px", borderRadius: "2px", background: "rgba(255,255,255,.08)", overflow: "hidden" }}>
                        <span style={{ display: "block", height: "100%", width: um.w, background: "linear-gradient(90deg,#7ce6ff,#a48bff)" }} />
                      </div>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "20px", paddingTop: "16px", borderTop: "1px solid rgba(255,255,255,.07)", fontSize: "12.5px", lineHeight: "1.6", color: "rgba(233,235,242,.5)" }}>
                {"Heatmaps, dead clicks, scroll depth, attention, WCAG audit, schema markup and Open Graph — generated with the site, explained in plain language."}
              </div>
            </div>
            {v.chapterProduct.map((cp, i0) => (
              <React.Fragment key={i0}>
                <div style={{ gridColumn: "span 3", minWidth: "0", padding: "22px 20px 24px", borderRadius: "18px", border: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.025)", display: "flex", flexDirection: "column", minHeight: "190px" }} className="orb-h8">
                  <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(124,230,255,.78)", letterSpacing: ".1em" }}>
                    {cp.n}
                  </div>
                  <div style={{ marginTop: "auto", fontFamily: "'Space Grotesk',sans-serif", fontSize: "17px", letterSpacing: "-.02em" }}>
                    {cp.t}
                  </div>
                  <div style={{ marginTop: "7px", fontSize: "12.5px", lineHeight: "1.55", color: "rgba(233,235,242,.5)" }}>
                    {cp.d}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
  );
}
