/* GENERATED by tools/port/port.mjs — do not edit by hand.
 *
 * Mechanical translation of the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 * Regenerate with: cd tools/port && node port.mjs
 */
import React from "react";
import type { Vals } from "../types";

export function ChapterInput({ v }: { v: Vals }) {
  return (
      <section style={{ position: "relative", padding: "56px 0 120px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", padding: "0 28px" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: "18px" }}>
            <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".18em", color: "rgba(124,230,255,.8)" }}>
              {"CHAPTER 01"}
            </span>
            <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(24px,3vw,38px)", letterSpacing: "-.03em" }}>
              {"Input"}
            </span>
            <span style={{ flex: "1", height: "1px", background: "linear-gradient(90deg,rgba(255,255,255,.16),transparent)" }} />
            <span style={{ fontSize: "13px", color: "rgba(233,235,242,.5)", maxWidth: "290px" }}>
              {"Eight ways in. Not one of them is a text box you have to be clever in."}
            </span>
          </div>
        </div>
        <div style={{ marginTop: "34px", overflowX: "auto", padding: "0 28px 10px", WebkitOverflowScrolling: "touch" }}>
          <div style={{ display: "flex", gap: "14px", minWidth: "min-content", maxWidth: "1180px", margin: "0 auto" }}>
            {v.chapterInput.map((ci, i0) => (
              <React.Fragment key={i0}>
                <div style={{ flex: "0 0 auto", width: "246px", height: "326px", padding: "20px", borderRadius: "16px", border: "1px solid rgba(255,255,255,.09)", background: ci.bg, display: "flex", flexDirection: "column", position: "relative", overflow: "hidden" }} className="orb-h4">
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".12em", color: "rgba(124,230,255,.8)" }}>
                      {ci.n}
                    </span>
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(233,235,242,.35)" }}>
                      {ci.k}
                    </span>
                  </div>
                  <div style={{ flex: "1", display: "flex", alignItems: "center", justifyContent: "center", padding: "14px 0" }}>
                    {ci.art}
                  </div>
                  <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "17px", letterSpacing: "-.02em" }}>
                    {ci.t}
                  </div>
                  <div style={{ marginTop: "7px", fontSize: "12.5px", lineHeight: "1.55", color: "rgba(233,235,242,.5)" }}>
                    {ci.d}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
  );
}
