/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function ChapterUnderstanding({ v }: { v: Vals }) {
  return (
      <section className="r-section" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: "18px", marginBottom: "34px" }}>
            <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".18em", color: "rgba(164,139,255,.85)" }}>
              {"CHAPTER 02"}
            </span>
            <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(24px,3vw,38px)", letterSpacing: "-.03em" }}>
              {"Understanding"}
            </span>
            <span style={{ flex: "1", height: "1px", background: "linear-gradient(90deg,rgba(255,255,255,.16),transparent)" }} />
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.05fr) minmax(0,.95fr)", gap: "44px", alignItems: "start" }} className="r-2col">
            <div style={{ borderTop: "1px solid rgba(255,255,255,.09)" }}>
              {v.chapterUnderstand.map((cu, i0) => (
                <React.Fragment key={i0}>
                  <div style={{ padding: "22px 0", borderBottom: "1px solid rgba(255,255,255,.07)", display: "grid", gridTemplateColumns: "48px 1fr", gap: "18px" }} className="orb-h5">
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", color: "rgba(164,139,255,.8)", paddingTop: "4px" }}>
                      {cu.n}
                    </span>
                    <div>
                      <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "19px", letterSpacing: "-.02em" }}>
                        {cu.t}
                      </div>
                      <div style={{ marginTop: "7px", fontSize: "13.5px", lineHeight: "1.6", color: "rgba(233,235,242,.52)", maxWidth: "430px" }}>
                        {cu.d}
                      </div>
                      <div style={{ marginTop: "10px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.34)" }}>
                        {cu.k}
                      </div>
                    </div>
                  </div>
                </React.Fragment>
              ))}
            </div>
            <div style={{ position: "sticky", top: "120px", padding: "24px", borderRadius: "18px", border: "1px solid rgba(255,255,255,.1)", background: "linear-gradient(168deg,rgba(20,18,38,.86),rgba(6,8,14,.92))" }} className="r-sticky">
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(233,235,242,.4)" }}>
                {"Design report · aurora.studio"}
              </div>
              <div style={{ marginTop: "20px", display: "flex", alignItems: "flex-end", gap: "12px" }}>
                <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "52px", lineHeight: ".9", letterSpacing: "-.04em" }}>
                  {"94"}
                </span>
                <span style={{ fontSize: "12px", color: "rgba(233,235,242,.45)", paddingBottom: "8px" }}>
                  {"design score · +3 since last edit"}
                </span>
              </div>
              <div style={{ marginTop: "22px", display: "flex", flexDirection: "column", gap: "14px" }}>
                {v.scores.map((sc, i0) => (
                  <React.Fragment key={i0}>
                    <div>
                      <div style={{ display: "flex", justifyContent: "space-between", fontSize: "12.5px", color: "rgba(233,235,242,.62)" }}>
                        <span>
                          {sc.t}
                        </span>
                        <span style={{ fontFamily: "'IBM Plex Mono',monospace", color: "rgba(233,235,242,.9)" }}>
                          {sc.v}
                        </span>
                      </div>
                      <div style={{ marginTop: "6px", height: "3px", borderRadius: "2px", background: "rgba(255,255,255,.08)", overflow: "hidden" }}>
                        <span style={{ display: "block", height: "100%", width: sc.w, background: "linear-gradient(90deg,#a48bff,#7ce6ff)" }} />
                      </div>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "22px", padding: "14px", borderRadius: "12px", border: "1px solid rgba(164,139,255,.28)", background: "rgba(164,139,255,.09)", fontSize: "12.5px", lineHeight: "1.6", color: "rgba(233,235,242,.75)" }}>
                {"“Your secondary CTA sits below AA at 3.1:1. Darkening it to "}
                <span style={{ fontFamily: "'IBM Plex Mono',monospace" }}>
                  {"#0B1522"}
                </span>
                {" fixes contrast without touching the palette.”"}
              </div>
            </div>
          </div>
        </div>
      </section>
  );
}
