/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function Comparison({ v }: { v: Vals }) {
  return (
      <section id="compare" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <h2 style={{ margin: "0 0 40px", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(28px,3.6vw,46px)", letterSpacing: "-.03em", lineHeight: "1.04" }}>
            {"Two workflows."}
            <br />
            {"One of them still has you typing."}
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))", gap: "22px" }}>
            <div style={{ padding: "28px 26px 30px", borderRadius: "20px", border: "1px solid rgba(255,255,255,.07)", background: "rgba(255,255,255,.018)" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".14em", color: "rgba(233,235,242,.4)" }}>
                  {"PROMPT-BASED TOOLS"}
                </span>
                <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", color: "rgba(255,150,140,.75)" }}>
                  {"~7 LOOPS"}
                </span>
              </div>
              <div style={{ marginTop: "24px", display: "flex", flexDirection: "column", gap: "0" }}>
                {v.oldFlow.map((of, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ display: "flex", alignItems: "center", gap: "14px", padding: "11px 0", borderBottom: "1px dashed rgba(255,255,255,.08)" }}>
                      <span style={{ width: "7px", height: "7px", borderRadius: "2px", background: of.dot }} />
                      <span style={{ fontSize: "13.5px", color: of.color }}>
                        {of.t}
                      </span>
                      <span style={{ flex: "1" }} />
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.3)" }}>
                        {of.k}
                      </span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "22px", fontSize: "13px", lineHeight: "1.6", color: "rgba(233,235,242,.45)" }}>
                {"Every fix is a fresh generation. Your copy, images and manual tweaks get overwritten on the way past."}
              </div>
            </div>
            <div style={{ padding: "28px 26px 30px", borderRadius: "20px", border: "1px solid rgba(124,230,255,.36)", background: "linear-gradient(160deg,rgba(124,230,255,.11),rgba(255,255,255,.02))" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".14em", color: "rgba(190,240,255,.9)" }}>
                  {"ORBITAL"}
                </span>
                <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", color: "rgba(150,255,200,.85)" }}>
                  {"1 PASS"}
                </span>
              </div>
              <div style={{ marginTop: "24px", display: "flex", flexDirection: "column", gap: "0" }}>
                {v.newFlow.map((nf, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ display: "flex", alignItems: "center", gap: "14px", padding: "11px 0", borderBottom: "1px solid rgba(255,255,255,.08)" }}>
                      <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "#7ce6ff", boxShadow: "0 0 10px rgba(124,230,255,.7)" }} />
                      <span style={{ fontSize: "13.5px", color: "rgba(233,235,242,.92)" }}>
                        {nf.t}
                      </span>
                      <span style={{ flex: "1" }} />
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(190,240,255,.7)" }}>
                        {nf.k}
                      </span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "22px", fontSize: "13px", lineHeight: "1.6", color: "rgba(233,235,242,.62)" }}>
                {"Nothing regenerates. Every instruction is a patch on a live tree, so what you already liked stays exactly as it was."}
              </div>
            </div>
          </div>
          <div style={{ marginTop: "22px", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: "0", borderTop: "1px solid rgba(255,255,255,.08)" }}>
            {v.uniqueCaps.map((uc, i0) => (
              <React.Fragment key={i0}>
                <div style={{ padding: "18px 18px 20px", borderRight: "1px solid rgba(255,255,255,.06)" }}>
                  <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", letterSpacing: ".1em", color: "rgba(124,230,255,.75)" }}>
                    {"ONLY HERE"}
                  </div>
                  <div style={{ marginTop: "10px", fontSize: "13.5px", lineHeight: "1.4", color: "rgba(233,235,242,.8)" }}>
                    {uc}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
  );
}
