/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function ConversationalEditing({ v }: { v: Vals }) {
  return (
      <section style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", display: "grid", gridTemplateColumns: "minmax(0,.92fr) minmax(0,1.08fr)", gap: "52px", alignItems: "center" }}>
          <div>
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "rgba(164,139,255,.8)" }}>
              {"Live conversational editing · F26"}
            </div>
            <h2 style={{ margin: "16px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(26px,3.2vw,42px)", letterSpacing: "-.03em", lineHeight: "1.05" }}>
              {"You don't regenerate."}
              <br />
              {"You keep talking."}
            </h2>
            <div style={{ marginTop: "26px", display: "flex", flexDirection: "column", gap: "10px" }}>
              {v.voiceLog.map((vl, i0) => (
                <React.Fragment key={i0}>
                  <div style={{ display: "flex", justifyContent: vl.align }}>
                    <div style={{ maxWidth: "84%", padding: "11px 14px", borderRadius: "14px", border: `1px solid ${vl.border}`, background: vl.bg, fontSize: "13.5px", lineHeight: "1.5", color: vl.color, opacity: vl.o, transition: "opacity .4s ease" }}>
                      {vl.t}
                    </div>
                  </div>
                </React.Fragment>
              ))}
            </div>
            <div style={{ marginTop: "24px", display: "flex", alignItems: "center", gap: "12px", padding: "12px 15px", borderRadius: "999px", border: "1px solid rgba(255,255,255,.1)", background: "rgba(255,255,255,.035)" }}>
              <span style={{ display: "flex", alignItems: "flex-end", gap: "2.5px", height: "18px" }}>
                <span style={{ width: "2.5px", height: "100%", borderRadius: "2px", background: "#7ce6ff", animation: "bar 1s ease-in-out infinite" }} />
                <span style={{ width: "2.5px", height: "100%", borderRadius: "2px", background: "#7ce6ff", animation: "bar 1s ease-in-out .12s infinite" }} />
                <span style={{ width: "2.5px", height: "100%", borderRadius: "2px", background: "#a48bff", animation: "bar 1s ease-in-out .24s infinite" }} />
                <span style={{ width: "2.5px", height: "100%", borderRadius: "2px", background: "#7ce6ff", animation: "bar 1s ease-in-out .36s infinite" }} />
              </span>
              <span style={{ fontSize: "13.5px", color: "rgba(233,235,242,.85)" }}>
                {v.voiceTyping}
                <span style={{ display: "inline-block", width: "7px", height: "14px", marginLeft: "2px", verticalAlign: "-2px", background: "#7ce6ff", animation: "caret 1s step-end infinite" }} />
              </span>
            </div>
          </div>
          <div style={{ position: "relative" }}>
            <div style={{ borderRadius: "16px", border: "1px solid rgba(255,255,255,.1)", background: v.vsBg, boxShadow: "0 40px 100px rgba(0,0,0,.6)", overflow: "hidden", transition: "background .8s ease" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "14px 18px", borderBottom: "1px solid rgba(255,255,255,.07)" }}>
                <span style={{ width: "14px", height: "14px", borderRadius: "50%", background: "linear-gradient(140deg,#8fe6ff,#a48bff)" }} />
                <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "13px" }}>
                  {"Aurora"}
                </span>
                <span style={{ flex: "1" }} />
                <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(124,230,255,.85)" }}>
                  {v.vsBadge}
                </span>
              </div>
              <div style={{ padding: v.vsPad, transition: "padding .8s ease" }}>
                <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(22px,2.6vw,34px)", lineHeight: "1.02", letterSpacing: "-.03em" }}>
                  {"Light, glass and"}
                  <br />
                  {"quiet rooms."}
                </div>
                <div style={{ marginTop: "12px", fontSize: "13px", color: "rgba(233,235,242,.55)", maxWidth: "300px" }}>
                  {"Architecture between Copenhagen and Kyoto."}
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: v.vsGap, marginTop: "24px", transition: "gap .8s ease" }}>
                  {v.vsCards.map((vc, i0) => (
                    <React.Fragment key={i0}>
                      <div style={{ padding: "16px 14px 18px", borderRadius: v.vsRadius, border: `1px solid ${v.vsCardBorder}`, background: v.vsCardBg, backdropFilter: v.vsBlur, transition: "all .8s ease" }}>
                        <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(196,236,255,.8)", letterSpacing: ".08em" }}>
                          {vc.k}
                        </div>
                        <div style={{ marginTop: "14px", fontSize: "13px" }}>
                          {vc.t}
                        </div>
                        <div style={{ marginTop: "6px", fontSize: "11.5px", lineHeight: "1.5", color: "rgba(233,235,242,.45)" }}>
                          {vc.d}
                        </div>
                      </div>
                    </React.Fragment>
                  ))}
                </div>
              </div>
            </div>
            <div style={{ marginTop: "16px", display: "flex", flexWrap: "wrap", gap: "8px" }}>
              {v.voiceSteps.map((vst, i0) => (
                <React.Fragment key={i0}>
                  <button onClick={vst.go} style={{ cursor: "pointer", padding: "8px 13px", borderRadius: "999px", border: `1px solid ${vst.border}`, background: vst.bg, color: vst.color, fontSize: "12px", fontFamily: "'IBM Plex Sans',sans-serif" }}>
                    {vst.t}
                  </button>
                </React.Fragment>
              ))}
            </div>
          </div>
        </div>
      </section>
  );
}
