/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import { activateOnKey } from "../a11y";
import type { Vals } from "../types";

export function Faq({ v }: { v: Vals }) {
  return (
      <section className="r-section" style={{ position: "relative", padding: "0 28px 120px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", display: "grid", gridTemplateColumns: "minmax(0,.9fr) minmax(0,1.1fr)", gap: "56px", alignItems: "start" }} className="r-2col">
          <div>
            <h2 style={{ margin: "0 0 26px", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(26px,3.2vw,40px)", letterSpacing: "-.03em" }}>
              {"Questions we get"}
              <br />
              {"in every demo."}
            </h2>
            <div style={{ borderTop: "1px solid rgba(255,255,255,.09)" }}>
              {v.faq.map((fq, i0) => (
                <React.Fragment key={i0}>
                  <div onClick={fq.go} role="button" tabIndex={0} onKeyDown={activateOnKey(fq.go)} aria-pressed={fq.on} style={{ padding: "18px 4px", borderBottom: "1px solid rgba(255,255,255,.08)", cursor: "pointer", display: "flex", gap: "14px", alignItems: "baseline", color: fq.color }} className="orb-h11">
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: fq.numColor }}>
                      {fq.n}
                    </span>
                    <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "16.5px", letterSpacing: "-.015em", lineHeight: "1.3" }}>
                      {fq.q}
                    </span>
                  </div>
                </React.Fragment>
              ))}
            </div>
          </div>
          <div aria-live="polite" style={{ position: "sticky", top: "130px", padding: "30px 28px 34px", borderRadius: "20px", border: "1px solid rgba(255,255,255,.09)", background: "linear-gradient(165deg,rgba(255,255,255,.05),rgba(255,255,255,.015))" }} className="r-sticky">
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", color: "rgba(124,230,255,.78)" }}>
              {v.faqTag}
            </div>
            <div style={{ marginTop: "18px", fontFamily: "'Space Grotesk',sans-serif", fontSize: "21px", letterSpacing: "-.02em", lineHeight: "1.25" }}>
              {v.faqQ}
            </div>
            <p style={{ margin: "16px 0 0", fontSize: "14.5px", lineHeight: "1.7", color: "rgba(233,235,242,.62)", textWrap: "pretty" }}>
              {v.faqA}
            </p>
          </div>
        </div>
      </section>
  );
}
