/* GENERATED by tools/port/port.mjs — do not edit by hand.
 *
 * Mechanical translation of the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 * Regenerate with: cd tools/port && node port.mjs
 */
import React from "react";
import type { Refs, Vals } from "../types";

export function Hero({ v, heroStageRef }: { v: Vals } & Pick<Refs, "heroStageRef">) {
  return (
<>
      <section id="top" style={{ position: "relative", padding: "172px 28px 40px" }}>
        <div style={{ position: "relative", zIndex: "3", maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".16em", textTransform: "uppercase", color: "rgba(233,235,242,.44)" }}>
            <span style={{ position: "relative", display: "block", width: "6px", height: "6px", borderRadius: "50%", background: "#7ce6ff" }}>
              <span style={{ position: "absolute", inset: "0", borderRadius: "50%", background: "#7ce6ff", animation: "pulseRing 2.6s ease-out infinite" }} />
            </span>
            {"\nMultimodal AI website engineer\n"}
            <span style={{ flex: "1", height: "1px", maxWidth: "180px", background: "linear-gradient(90deg,rgba(255,255,255,.18),transparent)" }} />
          </div>
          <h1 data-reveal="" style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(40px,5.6vw,78px)", lineHeight: ".98", letterSpacing: "-.035em", margin: "26px 0 0", maxWidth: "840px" }}>
            {"Stop describing it."}
            <br />
            {"Just "}
            <span style={{ fontFamily: "'Instrument Serif',serif", fontStyle: "italic", fontWeight: "400", color: "#cdeaff" }}>
              {"show"}
            </span>
            {" the machine what you mean."}
          </h1>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "44px", alignItems: "flex-end", marginTop: "34px" }}>
            <p data-reveal="" style={{ margin: "0", maxWidth: "430px", fontSize: "17px", lineHeight: "1.62", color: "rgba(233,235,242,.62)", textWrap: "pretty" }}>
              {"A sheet of paper, a phone camera, your voice, a note in the margin. Orbital reads intent the way an engineer does — and hands back a production website you can keep talking to."}
            </p>
            <div data-reveal="" style={{ display: "flex", gap: "11px" }}>
              <a href="#cta" style={{ display: "inline-flex", alignItems: "center", gap: "10px", padding: "14px 24px", borderRadius: "999px", fontSize: "15px", fontWeight: "500", color: "#04060c", background: "linear-gradient(180deg,#cdf3ff,#7ad6ff)", boxShadow: "0 14px 44px rgba(122,214,255,.3)" }} className="orb-h2">
                {"Start building "}
                <span style={{ fontFamily: "'IBM Plex Mono',monospace" }}>
                  {"→"}
                </span>
              </a>
              <a href="#demo" style={{ display: "inline-flex", alignItems: "center", gap: "11px", padding: "14px 22px", borderRadius: "999px", fontSize: "15px", border: "1px solid rgba(255,255,255,.13)", background: "rgba(255,255,255,.03)" }} className="orb-h3">
                <span style={{ display: "block", width: "20px", height: "20px", borderRadius: "50%", border: "1px solid rgba(255,255,255,.32)", position: "relative" }}>
                  <span style={{ position: "absolute", left: "7.5px", top: "5.5px", width: "0", height: "0", borderLeft: "6px solid rgba(255,255,255,.85)", borderTop: "4.5px solid transparent", borderBottom: "4.5px solid transparent" }} />
                </span>
                {"Watch the demo"}
              </a>
            </div>
          </div>
        </div>
        <div ref={heroStageRef} style={{ position: "relative", zIndex: "3", maxWidth: "1180px", margin: "78px auto 0" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "14px", paddingBottom: "16px", borderBottom: "1px solid rgba(255,255,255,.08)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(233,235,242,.38)" }}>
            <span>
              {"Session 0918 · live"}
            </span>
            <span style={{ flex: "1" }} />
            <span style={{ color: "rgba(124,230,255,.85)" }}>
              {v.hpLabel}
            </span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,.96fr) 132px minmax(0,1.18fr)", alignItems: "center", gap: "0", marginTop: "26px" }}>
            <div style={{ position: "relative", transform: "translateY(calc(var(--hp) * -26px)) rotate(calc(-2.4deg + var(--hp) * 1.9deg))", transition: "transform .1s linear" }}>
              <div style={{ position: "relative", padding: "26px 24px 30px", borderRadius: "3px", background: "linear-gradient(178deg,#f4f1e8,#e8e4d8)", boxShadow: "0 40px 90px rgba(0,0,0,.6),0 2px 0 rgba(255,255,255,.5) inset", color: "#3a3a36", overflow: "hidden" }}>
                <div style={{ position: "absolute", inset: "0", background: "repeating-linear-gradient(0deg,rgba(90,100,120,.09) 0 1px,transparent 1px 27px)", pointerEvents: "none" }} />
                <div style={{ position: "absolute", left: "0", top: "0", bottom: "0", width: "34px", borderRight: "1px solid rgba(200,90,80,.35)", pointerEvents: "none" }} />
                <div style={{ position: "relative", display: "flex", flexDirection: "column", gap: "12px" }}>
                  <div style={{ height: "30px", border: "2px solid #55565a", borderRadius: "3px", display: "flex", alignItems: "center", gap: "8px", padding: "0 9px", transform: "rotate(-.4deg)" }}>
                    <span style={{ width: "12px", height: "12px", border: "2px solid #6a6b6f", borderRadius: "50%" }} />
                    <span style={{ flex: "1" }} />
                    <span style={{ width: "26px", height: "5px", background: "#7a7b7f" }} />
                    <span style={{ width: "26px", height: "5px", background: "#7a7b7f" }} />
                    <span style={{ width: "44px", height: "15px", border: "2px solid #55565a", borderRadius: "3px" }} />
                  </div>
                  <div style={{ height: "112px", border: "2px solid #55565a", borderRadius: "3px", padding: "14px", display: "flex", flexDirection: "column", gap: "9px", transform: "rotate(.3deg)" }}>
                    <span style={{ width: "78%", height: "9px", background: "#6d6e72" }} />
                    <span style={{ width: "52%", height: "9px", background: "#8d8e92" }} />
                    <span style={{ width: "34%", height: "6px", background: "#a4a5a9", marginTop: "4px" }} />
                    <span style={{ width: "66px", height: "20px", border: "2px solid #55565a", borderRadius: "3px", marginTop: "6px" }} />
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "10px", height: "74px" }}>
                    <div style={{ border: "2px solid #55565a", borderRadius: "3px", transform: "rotate(-.6deg)" }} />
                    <div style={{ border: "2px solid #55565a", borderRadius: "3px", transform: "rotate(.5deg)" }} />
                    <div style={{ border: "2px solid #55565a", borderRadius: "3px", transform: "rotate(-.3deg)" }} />
                  </div>
                  <div style={{ height: "58px", border: "2px solid #55565a", borderRadius: "3px", position: "relative", overflow: "hidden", transform: "rotate(.2deg)" }}>
                    <span style={{ position: "absolute", left: "-10%", right: "-10%", top: "50%", height: "2px", background: "#6d6e72", transform: "rotate(-14deg)" }} />
                    <span style={{ position: "absolute", left: "-10%", right: "-10%", top: "50%", height: "2px", background: "#6d6e72", transform: "rotate(14deg)" }} />
                  </div>
                </div>
                <div style={{ position: "relative", marginTop: "16px", display: "flex", flexWrap: "wrap", gap: "10px 16px", fontFamily: "'Caveat',cursive", fontSize: "21px", color: "#2f3c56" }}>
                  <span style={{ transform: "rotate(-1.6deg)" }}>
                    {"dark background"}
                  </span>
                  <span style={{ transform: "rotate(1.1deg)" }}>
                    {"make this interactive"}
                  </span>
                  <span style={{ transform: "rotate(-.8deg)" }}>
                    {"add pricing"}
                  </span>
                  <span style={{ transform: "rotate(1.4deg)", color: "#8a3f2f" }}>
                    {"premium feel ✓"}
                  </span>
                </div>
                <div style={{ position: "absolute", left: "-1px", right: "-1px", height: "52%", top: "0", transform: "translateY(calc(var(--hp) * 190% - 40%))", background: "linear-gradient(180deg,transparent,rgba(124,230,255,.22))", borderBottom: "1px solid rgba(150,240,255,.85)", boxShadow: "0 0 40px rgba(124,230,255,.35)", pointerEvents: "none", opacity: "clamp(0,calc(var(--hp) * 5),1)" }} />
              </div>
              <div style={{ position: "absolute", left: "16px", bottom: "-26px", display: "flex", gap: "6px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".1em", color: "rgba(233,235,242,.4)" }}>
                <span>
                  {"INPUT · paper_sketch.jpg"}
                </span>
                <span style={{ color: "rgba(124,230,255,.8)" }}>
                  {"2048×1536"}
                </span>
              </div>
            </div>
            <div style={{ position: "relative", height: "290px", display: "flex", flexDirection: "column", justifyContent: "center", gap: "9px", padding: "0 10px" }}>
              <div style={{ position: "absolute", left: "0", right: "0", top: "50%", height: "1px", background: "repeating-linear-gradient(90deg,rgba(150,225,255,.55) 0 6px,transparent 6px 12px)", backgroundSize: "220px 1px", animation: "flowDash 3s linear infinite", opacity: "clamp(0,calc((var(--hp) - .1) * 4),1)" }} />
              {v.detections.map((d, i0) => (
                <React.Fragment key={i0}>
                  <div style={{ position: "relative", padding: "6px 8px", borderRadius: "6px", border: "1px solid rgba(124,230,255,.28)", background: "rgba(6,14,24,.82)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", lineHeight: "1.35", letterSpacing: ".02em", color: "rgba(196,236,255,.92)", opacity: d.o, transform: d.tr, transition: "opacity .35s ease,transform .35s ease" }}>
                    {d.t}
                  </div>
                </React.Fragment>
              ))}
            </div>
            <div style={{ position: "relative", transform: "translateY(calc(var(--hp) * 18px))" }}>
              <div style={{ position: "relative", borderRadius: "14px", border: "1px solid rgba(255,255,255,.1)", background: "linear-gradient(168deg,rgba(18,24,38,.96),rgba(8,11,18,.96))", boxShadow: "0 50px 120px rgba(0,0,0,.7)", overflow: "hidden" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "11px 14px", borderBottom: "1px solid rgba(255,255,255,.07)", background: "rgba(255,255,255,.02)" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "rgba(255,255,255,.14)" }} />
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "rgba(255,255,255,.14)" }} />
                  <span style={{ flex: "1", textAlign: "center", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.35)" }}>
                    {"aurora.studio"}
                  </span>
                  <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(124,230,255,.8)", opacity: "clamp(0,calc((var(--hp) - .55) * 5),1)" }}>
                    {"BUILT"}
                  </span>
                </div>
                <div style={{ padding: "20px", display: "flex", flexDirection: "column", gap: "16px" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "14px", opacity: "clamp(.12,calc((var(--hp) - .08) * 5),1)", transform: "translateY(calc((1 - clamp(0,calc((var(--hp) - .08) * 5),1)) * 8px))" }}>
                    <span style={{ width: "16px", height: "16px", borderRadius: "50%", background: "linear-gradient(140deg,#8fe6ff,#a48bff)" }} />
                    <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "14px", letterSpacing: "-.01em" }}>
                      {"Aurora"}
                    </span>
                    <span style={{ flex: "1" }} />
                    <span style={{ fontSize: "11.5px", color: "rgba(233,235,242,.5)" }}>
                      {"Work"}
                    </span>
                    <span style={{ fontSize: "11.5px", color: "rgba(233,235,242,.5)" }}>
                      {"Studio"}
                    </span>
                    <span style={{ fontSize: "11.5px", padding: "6px 12px", borderRadius: "999px", background: "#e9f6ff", color: "#08111c", fontWeight: "500" }}>
                      {"Enquire"}
                    </span>
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "1.15fr .85fr", gap: "16px", alignItems: "stretch" }}>
                    <div style={{ opacity: "clamp(.1,calc((var(--hp) - .2) * 5),1)", transform: "translateY(calc((1 - clamp(0,calc((var(--hp) - .2) * 5),1)) * 12px))" }}>
                      <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(20px,2.4vw,32px)", lineHeight: "1.02", letterSpacing: "-.03em" }}>
                        {"Light, glass"}
                        <br />
                        {"and quiet rooms."}
                      </div>
                      <div style={{ marginTop: "12px", fontSize: "12.5px", lineHeight: "1.55", color: "rgba(233,235,242,.55)", maxWidth: "250px" }}>
                        {"An architecture practice working between Copenhagen and Kyoto."}
                      </div>
                      <div style={{ display: "flex", gap: "8px", marginTop: "16px" }}>
                        <span style={{ fontSize: "11.5px", padding: "8px 14px", borderRadius: "999px", background: "linear-gradient(180deg,#d6f4ff,#8ad9ff)", color: "#08111c", fontWeight: "500" }}>
                          {"See the work"}
                        </span>
                        <span style={{ fontSize: "11.5px", padding: "8px 14px", borderRadius: "999px", border: "1px solid rgba(255,255,255,.16)", color: "rgba(233,235,242,.8)" }}>
                          {"Studio"}
                        </span>
                      </div>
                    </div>
                    <div style={{ borderRadius: "10px", border: "1px solid rgba(255,255,255,.09)", background: "repeating-linear-gradient(128deg,rgba(255,255,255,.06) 0 8px,rgba(255,255,255,.02) 8px 16px)", display: "flex", alignItems: "flex-end", padding: "10px", minHeight: "120px", opacity: "clamp(.08,calc((var(--hp) - .3) * 5),1)" }}>
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(233,235,242,.45)" }}>
                        {"studio photograph"}
                      </span>
                    </div>
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "12px", opacity: "clamp(.06,calc((var(--hp) - .42) * 5),1)", transform: "translateY(calc((1 - clamp(0,calc((var(--hp) - .42) * 5),1)) * 14px))" }}>
                    {v.heroCards.map((hc, i0) => (
                      <React.Fragment key={i0}>
                        <div style={{ padding: "13px", borderRadius: "10px", border: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.035)" }}>
                          <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(124,230,255,.75)", letterSpacing: ".08em" }}>
                            {hc.k}
                          </div>
                          <div style={{ marginTop: "10px", fontSize: "12.5px", color: "rgba(233,235,242,.9)" }}>
                            {hc.t}
                          </div>
                          <div style={{ marginTop: "5px", fontSize: "11px", lineHeight: "1.5", color: "rgba(233,235,242,.45)" }}>
                            {hc.d}
                          </div>
                        </div>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </div>
              <div style={{ position: "absolute", right: "14px", bottom: "-26px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".1em", color: "rgba(233,235,242,.4)" }}>
                {"OUTPUT · react + tailwind · "}
                <span style={{ color: "rgba(124,230,255,.8)" }}>
                  {"responsive"}
                </span>
              </div>
            </div>
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "0", marginTop: "64px", borderTop: "1px solid rgba(255,255,255,.08)" }}>
            {v.telemetry.map((tm, i0) => (
              <React.Fragment key={i0}>
                <div style={{ flex: "1", minWidth: "170px", padding: "18px 20px 20px", borderRight: "1px solid rgba(255,255,255,.06)" }}>
                  <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".12em", textTransform: "uppercase", color: "rgba(233,235,242,.36)" }}>
                    {tm.k}
                  </div>
                  <div style={{ marginTop: "9px", fontFamily: "'Space Grotesk',sans-serif", fontSize: "22px", letterSpacing: "-.02em" }}>
                    {tm.v}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
