/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import { activateOnKey } from "../a11y";
import type { Vals } from "../types";
import { InteractiveStage } from "./InteractiveStage";

export function HowItWorks({ v }: { v: Vals }) {
  const activeIndex = v.steps.findIndex((s) => s.on);
  const currentStepIndex = activeIndex >= 0 ? activeIndex : 0;

  return (
      <section className="r-section r-pad-lg" id="how" style={{ position: "relative", padding: "60px 28px 120px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", flexWrap: "wrap", gap: "30px", marginBottom: "44px" }}>
            <h2 style={{ margin: "0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(28px,3.6vw,46px)", letterSpacing: "-.03em", lineHeight: "1.04", maxWidth: "520px" }}>
              {"Six moves, and none of them"}
              <br />
              {"are typing a prompt."}
            </h2>
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".14em", color: "rgba(124,230,255,.9)", textTransform: "uppercase", background: "rgba(124,230,255,.08)", padding: "6px 12px", borderRadius: "999px", border: "1px solid rgba(124,230,255,.25)" }}>
              {"Scroll / Click to test · "}
              {v.stepReadout}
            </div>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1.15fr)", gap: "52px", alignItems: "start" }} className="r-2col">
            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {v.steps.map((s, i0) => (
                <React.Fragment key={i0}>
                  <div
                    ref={s.ref}
                    role="button"
                    tabIndex={0}
                    onKeyDown={activateOnKey(s.go)}
                    aria-pressed={s.on}
                    style={{
                      padding: "20px 22px",
                      borderRadius: "16px",
                      border: s.on ? "1px solid rgba(124,230,255,.4)" : "1px solid rgba(255,255,255,.06)",
                      background: s.on ? "linear-gradient(160deg,rgba(16,28,48,.85),rgba(8,12,22,.92))" : "rgba(255,255,255,.02)",
                      backdropFilter: "blur(12px)",
                      cursor: "pointer",
                      opacity: s.dim,
                      transition: "all .3s ease",
                      boxShadow: s.on ? "0 12px 36px rgba(0,0,0,.5), 0 0 20px rgba(124,230,255,.1)" : "none"
                    }}
                    className="orb-card-hover"
                    onClick={s.go}
                  >
                    <div style={{ display: "flex", alignItems: "baseline", gap: "16px" }}>
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", letterSpacing: ".14em", color: s.numColor, fontWeight: "500" }}>
                        {s.n}
                      </span>
                      <div style={{ flex: "1" }}>
                        <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "600", fontSize: "clamp(20px,2.4vw,28px)", letterSpacing: "-.025em", color: s.titleColor }}>
                          {s.t}
                        </div>
                        <div style={{ marginTop: "6px", fontSize: "13px", lineHeight: "1.55", color: s.on ? "rgba(233,235,242,.75)" : "rgba(233,235,242,.5)", maxWidth: "340px" }}>
                          {s.d}
                        </div>
                      </div>
                      <span style={{ width: s.on ? "28px" : "12px", height: "2px", borderRadius: "1px", background: s.rule, transition: "width .3s ease" }} />
                    </div>
                  </div>
                </React.Fragment>
              ))}
            </div>
            <div style={{ position: "sticky", top: "120px" }} className="r-sticky">
              <InteractiveStage
                stepIndex={currentStepIndex}
                stageTitle={v.stageTitle}
                stageMeta={v.stageMeta}
                stageLog={v.stageLog}
              />
            </div>
          </div>
        </div>
      </section>
  );
}
