/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function InteractiveDemo({ v }: { v: Vals }) {
  return (
      <section className="r-section" id="demo" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ maxWidth: "640px", marginBottom: "40px" }}>
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "rgba(124,230,255,.75)" }}>
              {"Interactive demo"}
            </div>
            <h2 style={{ margin: "16px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(30px,4vw,52px)", letterSpacing: "-.032em", lineHeight: "1.02" }}>
              {"Watch an idea become software."}
            </h2>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,.9fr) 210px minmax(0,1.25fr)", gap: "0", alignItems: "stretch", borderTop: "1px solid rgba(255,255,255,.09)", borderBottom: "1px solid rgba(255,255,255,.09)" }} className="r-demo">
            <div style={{ padding: "26px 26px 26px 0" }}>
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(233,235,242,.38)" }}>
                {"Input"}
              </div>
              <div style={{ marginTop: "16px", padding: "18px", borderRadius: "3px", background: "linear-gradient(178deg,#f2efe6,#e4e0d3)", color: "#3a3a36", boxShadow: "0 26px 60px rgba(0,0,0,.5)", transform: "rotate(-1.2deg)" }}>
                <div style={{ display: "flex", flexDirection: "column", gap: "9px" }}>
                  <div style={{ height: "22px", border: "2px solid #55565a", borderRadius: "2px" }} />
                  <div style={{ height: "70px", border: "2px solid #55565a", borderRadius: "2px" }} />
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "7px", height: "44px" }}>
                    <div style={{ border: "2px solid #55565a", borderRadius: "2px" }} />
                    <div style={{ border: "2px solid #55565a", borderRadius: "2px" }} />
                    <div style={{ border: "2px solid #55565a", borderRadius: "2px" }} />
                  </div>
                </div>
                <div style={{ marginTop: "12px", fontFamily: "'Caveat',cursive", fontSize: "19px", color: "#2f3c56" }}>
                  {"3 cards → pricing?"}
                </div>
              </div>
              <div style={{ marginTop: "22px", display: "flex", flexWrap: "wrap", gap: "7px" }}>
                {v.inputChips.map((ic, i0) => (
                  <React.Fragment key={i0}>
                    <span style={{ padding: "6px 10px", borderRadius: "999px", border: "1px solid rgba(255,255,255,.12)", background: "rgba(255,255,255,.035)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.62)" }}>
                      {ic}
                    </span>
                  </React.Fragment>
                ))}
              </div>
            </div>
            <div style={{ position: "relative", padding: "26px 18px", borderLeft: "1px solid rgba(255,255,255,.07)", borderRight: "1px solid rgba(255,255,255,.07)", background: "linear-gradient(180deg,rgba(124,230,255,.05),transparent 60%)" }}>
              <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(124,230,255,.7)" }}>
                {"Reasoning"}
              </div>
              <div style={{ marginTop: "16px", display: "flex", flexDirection: "column", gap: "9px" }}>
                {v.events.map((ev, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ display: "flex", gap: "8px", alignItems: "flex-start", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", lineHeight: "1.5", color: ev.color, animation: "ticker 4.2s ease forwards" }}>
                      <span style={{ color: "rgba(124,230,255,.7)" }}>
                        {ev.mark}
                      </span>
                      <span>
                        {ev.t}
                      </span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={{ marginTop: "20px", paddingTop: "14px", borderTop: "1px solid rgba(255,255,255,.07)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.42)" }}>
                {v.eventFooter}
              </div>
            </div>
            <div style={{ padding: "26px 0 26px 26px" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px" }}>
                <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", letterSpacing: ".14em", textTransform: "uppercase", color: "rgba(233,235,242,.38)" }}>
                  {"Output"}
                </div>
                <div style={{ display: "flex", gap: "5px" }}>
                  {v.devices.map((dv, i0) => (
                    <React.Fragment key={i0}>
                      <button onClick={dv.go} style={{ cursor: "pointer", padding: "5px 10px", borderRadius: "999px", border: `1px solid ${dv.border}`, background: dv.bg, color: dv.color, fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", letterSpacing: ".06em" }} className="r-touch">
                        {dv.t}
                      </button>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div style={{ marginTop: "16px", display: "flex", justifyContent: "center" }}>
                <div style={{ width: v.deviceW, transition: "width .6s cubic-bezier(.4,0,.2,1)", borderRadius: "14px", border: "1px solid rgba(255,255,255,.1)", background: "linear-gradient(168deg,#0e1420,#070a11)", boxShadow: "0 40px 100px rgba(0,0,0,.66)", overflow: "hidden" }} className="r-device-frame">
                  <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "13px 16px", borderBottom: "1px solid rgba(255,255,255,.06)" }}>
                    <span style={{ width: "14px", height: "14px", borderRadius: "50%", background: "linear-gradient(140deg,#8fe6ff,#a48bff)" }} />
                    <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "12.5px" }}>
                      {"Aurora"}
                    </span>
                    <span style={{ flex: "1" }} />
                    <span style={{ fontSize: "10.5px", color: "rgba(233,235,242,.45)" }}>
                      {"Plans"}
                    </span>
                    <span style={{ fontSize: "10.5px", padding: "5px 11px", borderRadius: "999px", background: "#e9f6ff", color: "#08111c" }}>
                      {"Enquire"}
                    </span>
                  </div>
                  <div style={{ padding: "22px 20px 24px" }}>
                    <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "26px", lineHeight: "1.04", letterSpacing: "-.03em" }}>
                      {"Three ways to"}
                      <br />
                      {"work with us."}
                    </div>
                    <div style={{ marginTop: "10px", fontSize: "12.5px", color: "rgba(233,235,242,.52)", maxWidth: "280px" }}>
                      {"Detected as pricing — because the note in the margin said so."}
                    </div>
                    <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "10px", marginTop: "20px" }}>
                      {v.outCards.map((oc, i0) => (
                        <React.Fragment key={i0}>
                          <div style={{ padding: "14px 12px 16px", borderRadius: "11px", border: `1px solid ${oc.border}`, background: oc.bg }}>
                            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", letterSpacing: ".1em", color: oc.tag }}>
                              {oc.k}
                            </div>
                            <div style={{ marginTop: "12px", fontFamily: "'Space Grotesk',sans-serif", fontSize: "20px", letterSpacing: "-.02em" }}>
                              {oc.p}
                            </div>
                            <div style={{ marginTop: "4px", fontSize: "10.5px", color: "rgba(233,235,242,.42)" }}>
                              {oc.per}
                            </div>
                            <div style={{ marginTop: "12px", height: "1px", background: "rgba(255,255,255,.08)" }} />
                            <div style={{ marginTop: "10px", fontSize: "11px", lineHeight: "1.5", color: "rgba(233,235,242,.55)" }}>
                              {oc.d}
                            </div>
                          </div>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
              <div style={{ marginTop: "18px", display: "flex", alignItems: "center", gap: "12px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.4)" }}>
                <span style={{ padding: "5px 9px", borderRadius: "6px", border: "1px solid rgba(143,230,255,.4)", color: "rgba(196,236,255,.9)" }}>
                  {"PRODUCTION READY"}
                </span>
                <span>
                  {"lighthouse 99 · a11y AA · 8 components"}
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
  );
}
