/* GENERATED by tools/port/port.mjs — do not edit by hand.
 *
 * Mechanical translation of the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 * Regenerate with: cd tools/port && node port.mjs
 */
import React from "react";
import type { Vals } from "../types";

export function Pricing({ v }: { v: Vals }) {
  return (
      <section id="pricing" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "24px", flexWrap: "wrap", paddingBottom: "22px", borderBottom: "1px solid rgba(255,255,255,.09)" }}>
            <h2 style={{ margin: "0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(26px,3.2vw,40px)", letterSpacing: "-.03em" }}>
              {"Priced like a tool."}
              <br />
              {"Works like a team."}
            </h2>
            <div style={{ fontSize: "13px", color: "rgba(233,235,242,.45)", maxWidth: "300px" }}>
              {"Every plan ships real code. The difference is how much intelligence runs before you do."}
            </div>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr) minmax(0,1fr)", gap: "0" }}>
            {v.plans.map((pl, i0) => (
              <React.Fragment key={i0}>
                <div style={{ padding: "30px 26px 34px", borderRight: "1px solid rgba(255,255,255,.07)", background: pl.bg }}>
                  <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
                    <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "17px" }}>
                      {pl.name}
                    </span>
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", letterSpacing: ".1em", color: pl.tagColor }}>
                      {pl.tag}
                    </span>
                  </div>
                  <div style={{ marginTop: "22px", display: "flex", alignItems: "baseline", gap: "7px" }}>
                    <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "40px", letterSpacing: "-.035em" }}>
                      {pl.price}
                    </span>
                    <span style={{ fontSize: "12.5px", color: "rgba(233,235,242,.42)" }}>
                      {pl.per}
                    </span>
                  </div>
                  <div style={{ marginTop: "24px", display: "flex", flexDirection: "column", gap: "11px" }}>
                    {pl.items.map((pi, i1) => (
                      <React.Fragment key={i1}>
                        <div style={{ display: "grid", gridTemplateColumns: "74px 1fr", gap: "12px", fontSize: "12.5px", lineHeight: "1.45" }}>
                          <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.35)", letterSpacing: ".06em" }}>
                            {pi.k}
                          </span>
                          <span style={{ color: "rgba(233,235,242,.7)" }}>
                            {pi.v}
                          </span>
                        </div>
                      </React.Fragment>
                    ))}
                  </div>
                  <a href="#cta" style={{ display: "block", marginTop: "28px", textAlign: "center", padding: "11px", borderRadius: "999px", fontSize: "13.5px", border: `1px solid ${pl.ctaBorder}`, background: pl.ctaBg, color: pl.ctaColor }} className="orb-h1">
                    {pl.cta}
                  </a>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
  );
}
