/* GENERATED by tools/port/port.mjs — do not edit by hand.
 *
 * Mechanical translation of the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 * Regenerate with: cd tools/port && node port.mjs
 */
import type { Refs } from "../types";

export function SiteHeader({ navRef }: Pick<Refs, "navRef">) {
  return (
<>
      <header ref={navRef} style={{ position: "fixed", top: "0", left: "0", right: "0", zIndex: "80", display: "flex", justifyContent: "center", padding: "18px 20px", transition: "padding .45s cubic-bezier(.4,0,.2,1)" }}>
        <nav style={{ display: "flex", alignItems: "center", gap: "8px", width: "100%", maxWidth: "1180px", padding: "10px 12px 10px 18px", border: "1px solid rgba(255,255,255,.08)", borderRadius: "999px", background: "rgba(8,10,16,.6)", backdropFilter: "blur(24px) saturate(1.5)", WebkitBackdropFilter: "blur(24px) saturate(1.5)", boxShadow: "0 18px 60px rgba(0,0,0,.5)" }}>
          <a href="#top" style={{ display: "flex", alignItems: "center", gap: "11px", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "600", fontSize: "15px", letterSpacing: "-.01em", marginRight: "14px" }}>
            <span style={{ position: "relative", display: "block", width: "18px", height: "18px", borderRadius: "50%", border: "1px solid rgba(160,225,255,.65)", boxShadow: "0 0 14px rgba(124,230,255,.35) inset" }}>
              <span style={{ position: "absolute", left: "50%", top: "50%", width: "6px", height: "6px", margin: "-3px 0 0 -3px", borderRadius: "50%", background: "#bdf1ff" }} />
            </span>
            {"\nOrbital"}
          </a>
          <span style={{ flex: "1" }} />
          <div style={{ display: "flex", gap: "4px", fontSize: "13px", color: "rgba(233,235,242,.6)" }}>
            <a href="#story" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"Product"}
            </a>
            <a href="#how" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"How it works"}
            </a>
            <a href="#workspace" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"Workspace"}
            </a>
            <a href="#chapters" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"Capabilities"}
            </a>
            <a href="#demo" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"Demo"}
            </a>
            <a href="#pricing" style={{ padding: "7px 11px", borderRadius: "999px", color: "inherit" }} className="orb-h0">
              {"Pricing"}
            </a>
          </div>
          <a href="#cta" style={{ marginLeft: "10px", fontSize: "13.5px", fontWeight: "500", padding: "10px 18px", borderRadius: "999px", color: "#04060c", background: "linear-gradient(180deg,#cdf3ff,#7ad6ff)", boxShadow: "0 8px 26px rgba(122,214,255,.32)" }} className="orb-h1">
            {"Start building"}
          </a>
        </nav>
      </header>
    </>
  );
}
