/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 *
 * Hand-added since the port: the mobile menu. The desktop bar below is
 * unchanged — the link row and the trigger are swapped by media query, so at
 * 769px and above this renders exactly what the export did.
 */
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { Refs } from "../types";

const LINKS = [
  ["#story", "Product"],
  ["#how", "How it works"],
  ["#workspace", "Workspace"],
  ["#chapters", "Capabilities"],
  ["#demo", "Demo"],
  ["#pricing", "Pricing"],
] as const;

const MENU_ID = "orbital-mobile-menu";

const SECTION_IDS = LINKS.map(([href]) => href.slice(1));

export function SiteHeader({ navRef }: Pick<Refs, "navRef">) {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState<string | null>(null);
  const frame = useRef(0);

  /* Which section the reader is currently in.
   *
   * Deliberately "the last section whose top has passed just below the bar"
   * rather than an IntersectionObserver on each anchor. Capabilities is a
   * block of six sections and only the first carries #chapters; an observer
   * would drop the highlight as soon as the reader scrolled past that first
   * short section. This keeps it lit for the whole block.
   */
  const syncActive = useCallback(() => {
    const y = window.scrollY + 120;
    let current: string | null = null;
    for (const id of SECTION_IDS) {
      const el = document.getElementById(id);
      if (!el) continue;
      if (el.getBoundingClientRect().top + window.scrollY <= y) current = id;
    }
    setActive(current);
  }, []);

  useEffect(() => {
    const onScroll = () => {
      cancelAnimationFrame(frame.current);
      frame.current = requestAnimationFrame(syncActive);
    };
    // Deferred to a frame rather than called inline: setting state
    // synchronously in an effect body triggers a cascading render, and this
    // also lets first layout settle before measuring.
    frame.current = requestAnimationFrame(syncActive);
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    return () => {
      cancelAnimationFrame(frame.current);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, [syncActive]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    // Resizing past the breakpoint hides the trigger, which would otherwise
    // strand the panel open with no way to dismiss it.
    const onResize = () => {
      if (window.innerWidth > 768) setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    window.addEventListener("resize", onResize);
    return () => {
      window.removeEventListener("keydown", onKey);
      window.removeEventListener("resize", onResize);
    };
  }, [open]);

  return (
    <>
      <header className="r-header" ref={navRef} style={{ position: "fixed", top: "0", left: "0", right: "0", zIndex: "80", display: "flex", justifyContent: "center", padding: "18px 20px", transition: "padding .45s cubic-bezier(.4,0,.2,1)" }}>
        <nav style={{ display: "flex", alignItems: "center", gap: "8px", width: "100%", maxWidth: "1180px", padding: "10px 12px 10px 18px", border: "1px solid rgba(255,255,255,.08)", borderRadius: "999px", background: "rgba(8,10,16,.6)", backdropFilter: "blur(24px) saturate(1.5)", WebkitBackdropFilter: "blur(24px) saturate(1.5)", boxShadow: "0 18px 60px rgba(0,0,0,.5)" }}>
          <a href="#top" style={{ display: "flex", alignItems: "center", gap: "11px", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "600", fontSize: "15px", letterSpacing: "-.01em", marginRight: "14px" }}>
            <span style={{ position: "relative", display: "block", width: "18px", height: "18px", borderRadius: "50%", border: "1px solid rgba(160,225,255,.65)", boxShadow: "0 0 14px rgba(124,230,255,.35) inset" }}>
              <span style={{ position: "absolute", left: "50%", top: "50%", width: "6px", height: "6px", margin: "-3px 0 0 -3px", borderRadius: "50%", background: "#bdf1ff" }} />
            </span>
            {"\nOrbital"}
          </a>
          <span style={{ flex: "1" }} />
          <div className="r-nav-links" style={{ display: "flex", gap: "4px", fontSize: "13px", color: "rgba(233,235,242,.6)" }}>
            {LINKS.map(([href, label]) => {
              const isActive = active === href.slice(1);
              return (
                <a
                  key={href}
                  href={href}
                  aria-current={isActive ? "true" : undefined}
                  style={{
                    padding: "7px 11px",
                    borderRadius: "999px",
                    color: isActive ? "#fff" : "inherit",
                    background: isActive ? "rgba(255,255,255,.07)" : "transparent",
                  }}
                  className="orb-h0"
                >
                  {label}
                </a>
              );
            })}
          </div>
          <a href="/sign-up" style={{ marginLeft: "10px", fontSize: "13.5px", fontWeight: "500", padding: "10px 18px", borderRadius: "999px", color: "#04060c", background: "linear-gradient(180deg,#cdf3ff,#7ad6ff)", boxShadow: "0 8px 26px rgba(122,214,255,.32)" }} className="orb-h1 r-nav-cta">
            {"Start building"}
          </a>

          {/* Trigger. Hidden above 768px; the link row takes its place. */}
          <button
            type="button"
            className="r-menu-trigger"
            aria-label={open ? "Close menu" : "Open menu"}
            aria-expanded={open}
            aria-controls={MENU_ID}
            onClick={() => setOpen((o) => !o)}
          >
            <span className="r-menu-bar" data-top="" />
            <span className="r-menu-bar" data-mid="" />
            <span className="r-menu-bar" data-bot="" />
          </button>
        </nav>

        {open ? (
          <div
            id={MENU_ID}
            className="r-menu-panel"
            // The nav pill is the visual anchor; this sits directly under it
            // and reuses the same glass treatment so it reads as one object.
          >
            {LINKS.map(([href, label]) => (
              <a
                key={href}
                href={href}
                className="r-menu-link"
                aria-current={active === href.slice(1) ? "true" : undefined}
                onClick={() => setOpen(false)}
              >
                {label}
              </a>
            ))}
          </div>
        ) : null}
      </header>

      {/* Dismiss layer. Rendered only while open, below the header's z-index
          but above the page, so a tap anywhere else closes the menu. */}
      {open ? (
        <div className="r-menu-scrim" aria-hidden="true" onClick={() => setOpen(false)} />
      ) : null}
    </>
  );
}
