/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */


export function SiteFooter() {
  return (
      <footer style={{ position: "relative", padding: "0 28px 56px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", paddingTop: "30px", borderTop: "1px solid rgba(255,255,255,.08)", display: "flex", flexWrap: "wrap", gap: "26px", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", fontFamily: "'Space Grotesk',sans-serif", fontSize: "14px" }}>
            <span style={{ position: "relative", display: "block", width: "16px", height: "16px", borderRadius: "50%", border: "1px solid rgba(160,225,255,.6)" }}>
              <span style={{ position: "absolute", left: "50%", top: "50%", width: "5px", height: "5px", margin: "-2.5px 0 0 -2.5px", borderRadius: "50%", background: "#bdf1ff" }} />
            </span>
            {"Orbital"}
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "20px", fontSize: "12.5px", color: "rgba(233,235,242,.42)" }}>
            <a href="#chapters" style={{ color: "inherit" }}>
              {"Capabilities"}
            </a>
            <a href="#workspace" style={{ color: "inherit" }}>
              {"Workspace"}
            </a>
            <a href="#demo" style={{ color: "inherit" }}>
              {"Demo"}
            </a>
            <a href="#pricing" style={{ color: "inherit" }}>
              {"Pricing"}
            </a>
            <a href="#compare" style={{ color: "inherit" }}>
              {"Comparison"}
            </a>
          </div>
          <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".08em", color: "rgba(233,235,242,.28)" }}>
            {"© 2026 ORBITAL ENGINEERING · BUILT FROM A NAPKIN"}
          </div>
        </div>
      </footer>
  );
}
