/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function Timeline({ v }: { v: Vals }) {
  return (
      <section className="r-section r-pad-lg" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto" }}>
          <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "rgba(124,230,255,.75)" }}>
            {"The future of website creation"}
          </div>
          <h2 style={{ margin: "16px 0 46px", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(28px,3.6vw,46px)", letterSpacing: "-.03em" }}>
            {"Prompting was a phase."}
          </h2>
          <div style={{ position: "relative", paddingLeft: "26px" }}>
            <div style={{ position: "absolute", left: "5px", top: "6px", bottom: "24px", width: "1px", background: "linear-gradient(180deg,rgba(255,255,255,.1),rgba(124,230,255,.7) 62%,rgba(164,139,255,.7))" }} />
            {v.era.map((er, i0) => (
              <React.Fragment key={i0}>
                <div data-reveal="" style={{ position: "relative", padding: "0 0 42px" }}>
                  <span style={{ position: "absolute", left: "-26px", top: "8px", width: "11px", height: "11px", borderRadius: "50%", background: er.dot, boxShadow: "0 0 0 4px rgba(3,4,8,1)" }} />
                  <div style={{ display: "grid", gridTemplateColumns: "110px minmax(0,1fr)", gap: "26px", alignItems: "baseline" }} className="r-timeline">
                    <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "26px", letterSpacing: "-.03em", color: er.year }}>
                      {er.y}
                    </div>
                    <div>
                      <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "20px", letterSpacing: "-.02em" }}>
                        {er.t}
                      </div>
                      <div style={{ marginTop: "8px", fontSize: "13.5px", lineHeight: "1.6", color: "rgba(233,235,242,.5)", maxWidth: "520px" }}>
                        {er.d}
                      </div>
                    </div>
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>
  );
}
