/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function Triad({ v }: { v: Vals }) {
  return (
      <section id="story" style={{ position: "relative", padding: "120px 28px 40px" }}>
        <div style={{ maxWidth: "1180px", margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: "0", borderTop: "1px solid rgba(255,255,255,.09)" }}>
          {v.triad.map((tr, i0) => (
            <React.Fragment key={i0}>
              <div data-reveal="" style={{ padding: "34px 30px 40px", borderRight: "1px solid rgba(255,255,255,.06)", position: "relative" }}>
                <div style={{ position: "absolute", top: "-5px", left: "0", width: "9px", height: "9px", borderRadius: "50%", background: tr.dot }} />
                <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", color: tr.label }}>
                  {tr.k}
                </div>
                <h3 style={{ margin: "20px 0 0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "26px", letterSpacing: "-.025em", lineHeight: "1.08" }}>
                  {tr.t}
                </h3>
                <p style={{ margin: "12px 0 0", fontSize: "14px", lineHeight: "1.62", color: "rgba(233,235,242,.55)", maxWidth: "290px" }}>
                  {tr.d}
                </p>
              </div>
            </React.Fragment>
          ))}
        </div>
      </section>
  );
}
