/* Originally generated by tools/port/port.mjs from the <x-dc> template in
 * reference/artifact-export/Orbital Launch.dc.html.
 *
 * The codemod is retired and refuses to run without --force. This file is
 * hand-maintained: regenerating would discard the accessibility,
 * reduced-motion and defect fixes applied after the port.
 *
 * reference/baselines/ is the guard. Run the parity check after any edit.
 */
import React from "react";
import type { Vals } from "../types";

export function Workspace({ v }: { v: Vals }) {
  return (
      <section id="workspace" style={{ position: "relative", padding: "0 28px 130px" }}>
        <div style={{ maxWidth: "1240px", margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "30px", flexWrap: "wrap", marginBottom: "34px" }}>
            <h2 style={{ margin: "0", fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(28px,3.6vw,46px)", letterSpacing: "-.03em", lineHeight: "1.04" }}>
              {"The room where it happens."}
            </h2>
            <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", letterSpacing: ".14em", color: "rgba(233,235,242,.36)", textTransform: "uppercase" }}>
              {"Workspace · build 2026.8"}
            </div>
          </div>
          <div style={{ border: "1px solid rgba(255,255,255,.1)", borderRadius: "20px", background: "rgba(6,8,14,.86)", boxShadow: "0 50px 130px rgba(0,0,0,.66)", overflow: "hidden" }}>
            <div style={{ display: "grid", gridTemplateColumns: "212px minmax(0,1fr) 316px", minHeight: "600px" }}>
              <aside style={{ borderRight: "1px solid rgba(255,255,255,.07)", padding: "18px 12px", display: "flex", flexDirection: "column", gap: "2px", background: "rgba(255,255,255,.015)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "9px", padding: "6px 10px 16px" }}>
                  <span style={{ width: "15px", height: "15px", borderRadius: "50%", border: "1px solid rgba(160,225,255,.6)", position: "relative" }}>
                    <span style={{ position: "absolute", left: "50%", top: "50%", width: "5px", height: "5px", margin: "-2.5px 0 0 -2.5px", borderRadius: "50%", background: "#bdf1ff" }} />
                  </span>
                  <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "13.5px" }}>
                    {"Aurora Labs"}
                  </span>
                </div>
                {v.navItems.map((ni, i0) => (
                  <React.Fragment key={i0}>
                    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 11px", borderRadius: "8px", fontSize: "13px", color: ni.color, background: ni.bg, cursor: "pointer" }} className="orb-h9">
                      <span>
                        {ni.t}
                      </span>
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(233,235,242,.3)" }}>
                        {ni.c}
                      </span>
                    </div>
                  </React.Fragment>
                ))}
                <span style={{ flex: "1" }} />
                <div style={{ padding: "12px", borderRadius: "12px", border: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.025)" }}>
                  <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", letterSpacing: ".1em", color: "rgba(233,235,242,.4)" }}>
                    {"PROJECT MEMORY · F16"}
                  </div>
                  <div style={{ marginTop: "10px", display: "flex", flexDirection: "column", gap: "7px" }}>
                    {v.memory.map((mi, i0) => (
                      <React.Fragment key={i0}>
                        <div style={{ display: "flex", gap: "8px", fontSize: "11px", color: "rgba(233,235,242,.55)" }}>
                          <span style={{ fontFamily: "'IBM Plex Mono',monospace", color: "rgba(124,230,255,.7)" }}>
                            {mi.d}
                          </span>
                          {mi.t}
                        </div>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </aside>
              <div style={{ display: "flex", flexDirection: "column", minWidth: "0" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "11px 16px", borderBottom: "1px solid rgba(255,255,255,.07)" }}>
                  <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", color: "rgba(233,235,242,.42)" }}>
                    {"aurora.studio / home"}
                  </span>
                  <span style={{ flex: "1" }} />
                  {v.devices.map((dv2, i0) => (
                    <React.Fragment key={i0}>
                      <button onClick={dv2.go} style={{ cursor: "pointer", padding: "5px 10px", borderRadius: "7px", border: `1px solid ${dv2.border}`, background: dv2.bg, color: dv2.color, fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px" }}>
                        {dv2.t}
                      </button>
                    </React.Fragment>
                  ))}
                </div>
                <div style={{ flex: "1", padding: "26px", display: "flex", justifyContent: "center", background: "radial-gradient(700px 340px at 50% -10%,rgba(124,230,255,.06),transparent 70%)" }}>
                  <div style={{ width: v.deviceW, transition: "width .6s cubic-bezier(.4,0,.2,1)", borderRadius: "14px", border: "1px solid rgba(255,255,255,.09)", background: "linear-gradient(170deg,#0d1420,#070a11)", overflow: "hidden", position: "relative" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "14px 18px", borderBottom: "1px solid rgba(255,255,255,.06)" }}>
                      <span style={{ width: "14px", height: "14px", borderRadius: "50%", background: "linear-gradient(140deg,#8fe6ff,#a48bff)" }} />
                      <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "12.5px" }}>
                        {"Aurora"}
                      </span>
                      <span style={{ flex: "1" }} />
                      <span style={{ fontSize: "11px", color: "rgba(233,235,242,.45)" }}>
                        {"Work"}
                      </span>
                      <span style={{ fontSize: "11px", color: "rgba(233,235,242,.45)" }}>
                        {"Studio"}
                      </span>
                      <span style={{ fontSize: "11px", padding: "6px 12px", borderRadius: "999px", background: "#e9f6ff", color: "#08111c" }}>
                        {"Enquire"}
                      </span>
                    </div>
                    <div style={{ padding: "26px 22px 24px", position: "relative" }}>
                      <div style={{ position: "absolute", top: "14px", right: "14px", padding: "3px 8px", borderRadius: "6px", border: "1px dashed rgba(124,230,255,.55)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "9px", color: "rgba(190,240,255,.9)" }}>
                        {"hero · selected"}
                      </div>
                      <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: "500", fontSize: "clamp(24px,3vw,38px)", lineHeight: "1.02", letterSpacing: "-.032em", maxWidth: "420px" }}>
                        {"Light, glass and quiet rooms."}
                      </div>
                      <div style={{ marginTop: "14px", fontSize: "13.5px", lineHeight: "1.6", color: "rgba(233,235,242,.55)", maxWidth: "330px" }}>
                        {"An architecture practice working between Copenhagen and Kyoto, mostly in daylight."}
                      </div>
                      <div style={{ display: "flex", gap: "10px", marginTop: "20px" }}>
                        <span style={{ fontSize: "12.5px", padding: "10px 18px", borderRadius: "999px", background: "linear-gradient(180deg,#d6f4ff,#8ad9ff)", color: "#08111c", fontWeight: "500" }}>
                          {"See the work"}
                        </span>
                        <span style={{ fontSize: "12.5px", padding: "10px 18px", borderRadius: "999px", border: "1px solid rgba(255,255,255,.16)", color: "rgba(233,235,242,.82)" }}>
                          {"Studio"}
                        </span>
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "1.2fr .8fr", gap: "14px", marginTop: "26px" }}>
                        <div style={{ borderRadius: "12px", border: "1px solid rgba(255,255,255,.08)", background: "repeating-linear-gradient(128deg,rgba(255,255,255,.06) 0 9px,rgba(255,255,255,.02) 9px 18px)", minHeight: "150px", display: "flex", alignItems: "flex-end", padding: "12px", fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(233,235,242,.42)" }}>
                          {"interior photograph"}
                        </div>
                        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                          {v.heroCards.map((wc, i0) => (
                            <React.Fragment key={i0}>
                              <div style={{ flex: "1", padding: "12px", borderRadius: "11px", border: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.03)" }}>
                                <div style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9px", color: "rgba(124,230,255,.72)" }}>
                                  {wc.k}
                                </div>
                                <div style={{ marginTop: "8px", fontSize: "12px" }}>
                                  {wc.t}
                                </div>
                              </div>
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", padding: "14px 16px", borderTop: "1px solid rgba(255,255,255,.07)", background: "rgba(255,255,255,.022)" }}>
                  {v.dock.map((dk, i0) => (
                    <React.Fragment key={i0}>
                      <span style={{ display: "inline-flex", alignItems: "center", gap: "8px", padding: "9px 13px", borderRadius: "10px", border: "1px solid rgba(255,255,255,.09)", background: "rgba(255,255,255,.035)", fontSize: "12.5px", color: "rgba(233,235,242,.75)", cursor: "pointer" }} className="orb-h10">
                        <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: dk.dot }} />
                        {dk.t}
                      </span>
                    </React.Fragment>
                  ))}
                  <span style={{ flex: "1" }} />
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "8px", padding: "9px 14px", borderRadius: "10px", background: "rgba(124,230,255,.12)", border: "1px solid rgba(124,230,255,.4)", fontFamily: "'IBM Plex Mono',monospace", fontSize: "11px", color: "#cdf2ff" }}>
                    {"DEPLOY ⌘⏎"}
                  </span>
                </div>
              </div>
              <aside style={{ borderLeft: "1px solid rgba(255,255,255,.07)", display: "flex", flexDirection: "column", background: "rgba(255,255,255,.015)" }}>
                <div style={{ padding: "14px 16px", borderBottom: "1px solid rgba(255,255,255,.07)", display: "flex", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "#7ce6ff", boxShadow: "0 0 12px rgba(124,230,255,.8)" }} />
                  <span style={{ fontSize: "13px" }}>
                    {"AI engineer"}
                  </span>
                  <span style={{ flex: "1" }} />
                  <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "9.5px", color: "rgba(233,235,242,.35)" }}>
                    {"reasoning"}
                  </span>
                </div>
                <div style={{ flex: "1", padding: "14px", display: "flex", flexDirection: "column", gap: "8px", overflow: "hidden" }}>
                  {v.wsEvents.map((we, i0) => (
                    <React.Fragment key={i0}>
                      <div style={{ display: "flex", gap: "9px", alignItems: "flex-start", fontFamily: "'IBM Plex Mono',monospace", fontSize: "10.5px", lineHeight: "1.5", color: we.color }}>
                        <span style={{ color: "rgba(124,230,255,.65)" }}>
                          {we.mark}
                        </span>
                        <span>
                          {we.t}
                        </span>
                      </div>
                    </React.Fragment>
                  ))}
                  <div style={{ marginTop: "10px", paddingTop: "12px", borderTop: "1px solid rgba(255,255,255,.07)", display: "flex", flexDirection: "column", gap: "10px" }}>
                    {v.chat.map((ch, i0) => (
                      <React.Fragment key={i0}>
                        <div style={{ alignSelf: ch.align, maxWidth: "88%", padding: "10px 12px", borderRadius: "12px", border: `1px solid ${ch.border}`, background: ch.bg, fontSize: "12.5px", lineHeight: "1.5", color: ch.color }}>
                          {ch.t}
                        </div>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <div style={{ padding: "13px", borderTop: "1px solid rgba(255,255,255,.07)" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "10px 12px", borderRadius: "10px", border: "1px solid rgba(255,255,255,.09)", background: "rgba(255,255,255,.035)", fontSize: "12.5px", color: "rgba(233,235,242,.4)" }}>
                    {"Speak or type an edit…"}
                    <span style={{ flex: "1" }} />
                    <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: "10px", color: "rgba(124,230,255,.8)" }}>
                      {"⌘K"}
                    </span>
                  </div>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </section>
  );
}
